- src/routes/InventoryTable.js
> Do not add health and other filters

- src/App.scss
- src/routes/InventoryTable.js
> Hide checkboxes since we do not allow any actions

- package-lock.json
- package.json
adds remediation buttons https://github.com/RedHatInsights/insights-frontend-components/pull/297
> bump frontend-components to 3.33.65

- src/routes/InventoryTable.js
Is related to https://github.com/RedHatInsights/insights-frontend-components/pull/310
> Call refresh data when pagination changes

- package-lock.json
- package.json
Using the latest version of insights-frontend-components should fix the
problems displaying the compliance tab.
https://github.com/RedHatInsights/insights-frontend-components/pull/300
> Fix compliance tab

- src/store/reducers.js
Keeping up with our name changes.
https://projects.engineering.redhat.com/browse/RHIADVISOR-440
> Update 'Configuration Assessment' to 'Insights'

- package-lock.json
- package.json
- src/store/reducers.js
> Reorder tabs in application detail

- src/store/reducers.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-718
related to https://github.com/RedHatInsights/insights-inventory-frontend/issues/77
> Renames 'Rules' to 'Insights'

- package-lock.json
- package.json
> bumping package

- src/components/inventory/AsyncInventory.js
- src/routes/InventoryDetail.js
- src/routes/inventory.scss
> Update styles for general info

- src/routes/InventoryTable.js
> Remove download button

- package-lock.json
- package.json
includes https://github.com/RedHatInsights/insights-frontend-components/pull/413
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-1117
> Include fix to Insights tab system report list cannibalization 

- config/dev.webpack.config.js
- config/setupTests.js
- package-lock.json
- src/actions.js
- src/actions.test.js
- src/api.js
- src/routes/InventoryDetail.js
- src/routes/InventoryTable.js
- src/store/reducers.js
> [WIP] Hide not entitled tabs in inventory detail

- package-lock.json
- package.json
includes https://github.com/RedHatInsights/frontend-components/pull/58
bz https://bugzilla.redhat.com/show_bug.cgi?id=1721265
> Ensures correct sanitization of >, <, &

- package-lock.json
- package.json
- src/actions.js
- src/api.js
- src/constants.js
- src/routes/InventoryTable.js
- src/routes/inventory.scss
> Add delete operation to inventory table

- src/store/reducers.js
I have not tested this change, I believe it is the only change required to change the text on the tab to "Vulnerability".
> Rename "Vulnerabilities" to "Vulnerability"

- package-lock.json
- package.json
Adding the most recent changes from inventory-insights
> Updates inv-insights app

- package-lock.json
- package.json
Meant to fix RHICOMPL-268 in the inventory compliance tab
> Update inventory-compliance to 0.0.15

- package-lock.json
- package.json
This is meant to include rules and references - https://github.com/RedHatInsights/frontend-components/pull/94
> Update inventory-compliance to 0.0.16

- package-lock.json
- package.json
hoping to get ahead of this bug showing up on prod
> Update inventory-insights app to include recent dropdown fixes

- package-lock.json
- package.json
includes https://github.com/RedHatInsights/frontend-components/pull/137
> Fixes inv-insights table sorting

- package-lock.json
- package.json
includes https://github.com/RedHatInsights/frontend-components/pull/205
> Update inv-insights app

- package-lock.json
- package.json
includes https://github.com/RedHatInsights/frontend-components/pull/216
> Updates inv-insights plugin, includes satellite_managed adjustment

- package-lock.json
- package.json
> Updates inv-insights plugin, includes bugfixes and new toolbar

- src/actions.js
- src/components/DeleteModal.js
- src/constants.js
- src/routes/InventoryTable.js
- src/store/reducers.js
- src/store/reducers.test.js
**None selected**
**1 selected**
**Curr page selected**
**Some on curr page not selected**
**Selected options**
> Allow cross select on multiple pages

- package-lock.json
- src/routes/InventoryTable.js
- src/routes/inventory.scss
This is a hot fix to enable delete button meanwhile chrome is preparing for update.
> Re-enable delete button

- src/store/reducers.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5794
oof, reorders deps, missed that
> Whats new is old, lets do #80 again, rename Insights to Advisor

- src/routes/InventoryTable.js
Changed delete BTN in InventoryTable to variant "secondary"
@karelhala
> Change delete btn in InventoryTable to "secondary"

- package-lock.json
- package.json
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6521
> Fix bulk select check calculation, isSelected calculated off rule_id 

- package-lock.json
- package.json
Co-authored-by: Katerina Patticha <apattich@localhost.localdomain>
> Update Vuln package version (#555) prod-beta

- package-lock.json
- package.json
Co-authored-by: Katerina Patticha <apattich@localhost.localdomain>
> Update Vuln package version (#555) ci-stable

- package-lock.json
- package.json
Co-authored-by: Katerina Patticha <apattich@localhost.localdomain>
> Update Vuln package version (#555) qa-beta

- src/routes/InventoryTable.js
part of https://issues.redhat.com/browse/RHCLOUD-9754
**Before**
**After**
> Limit table actions for users with permissions

- src/App.js
- src/Routes.js
- src/routes/InventoryTable.js
With the new global filter bookmarks we have to pass hash partial to router as well.
If user selects `Workloads = SAP` in global filter we have to pass this to inventory as `filter` with `sap_system: true`
> Pass sap filter to inventory component

- package-lock.json
- package.json
- src/hooks/useInventoryWritePermissions.js
- src/routes/InventoryDetail.js
- src/routes/InventoryTable.js
Part of https://issues.redhat.com/browse/RHCLOUD-9754
- Hides delete/edit name buttons in detail
**Before**
**After**
TODO:
> Hide delete button in detail

- src/routes/InventoryTable.js
> consume selected SIDs

- src/App.js
- src/hooks/useInventoryWritePermissions.js
- src/store/permissions/reducer.js
- src/store/permissions/reducer.test.js
* Enable RBAC everywhere
* Remove redundant test
> Enable RBAC everywhere - prod-beta

- src/App.js
- src/hooks/useInventoryWritePermissions.js
- src/store/permissions/reducer.js
- src/store/permissions/reducer.test.js
* Enable RBAC everywhere
* Remove redundant test
> Enable RBAC everywhere - master-stable

- src/App.js
- src/hooks/useInventoryWritePermissions.js
- src/store/permissions/reducer.js
- src/store/permissions/reducer.test.js
* Enable RBAC everywhere
* Remove redundant test
> Enable RBAC everywhere - prod-stable

- src/index.html
- src/routes/InventoryDetail.js
- src/routes/InventoryTable.js
https://issues.redhat.com/browse/RHCLOUD-10547
> update tab titles

- package-lock.json
- package.json
See https://github.com/RedHatInsights/frontend-components/pull/888
> Update general info to include modal variants

- config/dev.webpack.config.js
- package-lock.json
- package.json
see https://github.com/RedHatInsights/frontend-components/pull/893
+ alias in dev version for reactRedux
> Update general info to fix search

- babel.config.js
- package-lock.json
- package.json
- src/routes/InventoryTable.js
- src/store/index.js
- src/store/reducers.js
Do not merge, before https://github.com/RedHatInsights/frontend-components/pull/904
> Update notifications package [WIP]

- config/dev.webpack.config.js
- package-lock.json
- package.json
- src/App.js
- src/AppEntry.js
- src/Routes.js
- src/components/inventory/Vulnerability.js
- src/routes/InventoryDetail.js
- src/routes/InventoryTable.js
- src/store/index.js
Since we want to make getRegistry non singleton this PR aims to do so trough provider.
> Add context for getRegistry

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- package-lock.json
- package.json
The patchman dependencies were causing issues with the html webpack plugin. I had to add a direct dependency, dedupe dependencies, and alias to fix the HTML build.
Long term fix is here: https://github.com/RedHatInsights/patchman-ui/pull/457
We also need a new version of patch inventory to be installed
> Hotifx build

- src/components/inventory/Vulnerability.js
for some reason `useParams` was empty. I replaced it with `useParams`
> fix(vulnerability): Fix undefined inventoryId

- src/components/inventory/Compliance.js
> fix(compliance):  Fix undefined inventoryId

- package-lock.json
- package.json
- src/components/inventory/Patch.js
- src/components/inventory/index.js
- src/routes/InventoryDetail.js
- src/store/reducers.js
> Migrate patch to use federated modules

- src/components/inventory/Ros.js
- src/components/inventory/index.js
- src/store/reducers.js
ROS side PR - https://github.com/RedHatInsights/ros-frontend/pull/40
+ adding @karelhala into loop for review.
> ros tab to use fed modules

- src/store/reducers.js
With [JIRA card](https://issues.redhat.com/browse/RHIROS-201), removing ros specific cookie check from respective repositories.
+adding @karelhala into loop.
> remove cookie check for ROS tab

- src/components/SpinnerFallback.js
- src/components/inventory/Ros.js
- src/components/inventory/index.js
- src/store/reducers.js
> Add ROS table for prod-beta

- src/components/InventoryTable/TitleColumn.js
- src/components/InventoryTable/TitleColumn.test.js
more info: https://github.com/RedHatInsights/frontend-components/pull/1218
> Fix open new tab link event.

- package-lock.json
- package.json
- src/components/SystemDetails/Advisor.js
- src/components/SystemDetails/Patch.js
- src/components/SystemDetails/Ros.js
- src/components/SystemDetails/Vulnerability.js
fixes https://github.com/RedHatInsights/insights-inventory-frontend/issues/1337
- Do not pass custom fallback as it is the same as the default one - see [here](https://github.com/RedHatInsights/frontend-components/blob/4ced0642a1fd6ed4f01a93fd4fe660318f5116b3/packages/components/src/AsyncComponent/index.js#L50)
**Before**
**After**
> Fix loading state between applications sections

- package-lock.json
- package.json
- src/components/InventoryTable/InventoryTable.js
- replace `activeFiltersConfig` force override with prop extension
> Add missing filter chips

- package-lock.json
- package.json
- src/components/GeneralInfo/InfoTable/__snapshots__/InfoTable.test.js.snap
> [STABLE] Update FEC to fix issues in compliance

- src/store/reducers.js
This PR can be merged once ROS is deployed to prod-stable env: https://github.com/RedHatInsights/cloud-services-config/pull/1012
cc @PreetiW
> Enable ROS tab in production.

- deploy/frontend.yaml
* add back deploymentRepo key to FE template
> Fix frontend deployment repo

- src/components/InventoryTable/EntityTable.js
Closes [ADVISOR-1849](https://issues.redhat.com/browse/ADVISOR-1849)
> Removes actions toggle when table is empty

- src/routes/InventoryTable.js
Fixes: https://issues.redhat.com/browse/ESSNTL-2122.
It is easy to test. Just run the PR locally and apply 'Ansible Automation Platform' global filter.
> EESNTL-2112: apply APP glogabl-filter

- src/components/InventoryTable/NoSystemsTable.js
- src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
- src/components/InventoryTable/__snapshots__/InventoryList.test.js.snap
- src/components/InventoryTable/__snapshots__/NoSystemsTable.test.js.snap
> fix: updated no results text

- src/routes/InventoryTable.js
Chrome service recently added new filter to global filter https://github.com/RedHatInsights/insights-chrome/pull/1776 so let's pass it down the foodchain. This PR is similiar to https://github.com/RedHatInsights/insights-inventory-frontend/pull/1491
> Add mssql global filter option

- src/routes/InventoryTable.js
Taken from the PRs merged to prod-beta. These need to be merged for the fix to work in prod stable.
> AAP & MSSQL filter fixes to Prod Stable

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- package-lock.json
- package.json
- src/Utilities/OperatingSystemFilterHelpers.js
- src/Utilities/OperatingSystemFilterHelpers.test.js
- src/Utilities/__snapshots__/OperatingSystemFilterHelpers.test.js.snap
- src/api/api.js
- src/api/tagsApi.test.js
- src/components/InventoryTable/EntityTableToolbar.js
- src/components/InventoryTable/EntityTableToolbar.test.js
- src/components/InventoryTable/InventoryTable.test.js
- src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
- src/components/InventoryTable/helpers.js
- src/components/filters/__snapshots__/useOperatingSystemFilter.test.js.snap
- src/components/filters/useOperatingSystemFilter.js
- src/components/filters/useOperatingSystemFilter.test.js
- src/modules/OsFilterHelpers.js
- src/routes/InventoryTable.js
This turns the OS filter into a grouped filter:
https://user-images.githubusercontent.com/7757/157241899-56b37052-bafe-4e70-a5f4-1aa1f978cf80.mp4
> feat(InventoryTable): RHIF-18 - Update OS filter to groups

- package-lock.json
- package.json
- src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
This is to fix the skeletonTable component, which was fixed here: https://github.com/RedHatInsights/frontend-components/pull/1498
> Bump @redhat-cloud-services/frontend-components to v3.8.4

- src/Utilities/InsightsDisconnected.js
- src/components/InventoryDetail/InsightsPrompt.js
- src/components/InventoryDetail/InventoryDetail.js
[ESSNTL-2118: Insights tether CTA](https://issues.redhat.com/browse/ESSNTL-2118): 
Component created  in Inventory Detauls page by this PR (a long space between last seen date and tethering icon exists on stage/beta, needs to be fixed later):
Hosts which are not connected to Insights have an updated tooltip:
> Insights Tethering 

- build_deploy.sh
- pr_check.sh
* `IMAGE` now matches quay 
* `COMPONENT` now matches app-interface folder
> Fix image name and component

- package-lock.json
- package.json
- src/Utilities/constants.js
- src/api/api.js
- src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
- src/components/filters/useRegisteredWithFilter.test.js
Merges `master` into `master-stable`.
> Update master-stable with latest changes

- src/components/InventoryDetail/InsightsPrompt.js
This PR is being created to address [ESSNTL-3131](https://issues.redhat.com/browse/ESSNTL-3131). It just updates the commands in the Client Setup card.
> Fix client setup commands for unregistered hosts

- src/components/InventoryDetail/InsightsPrompt.js
This fixes: https://issues.redhat.com/browse/RHIF-54.
Please refer the ticket for more info.
> fix(RHIF-54): fix the command for insights-client install

- config/dev.webpack.config.js
- config/prod.webpack.config.js
master-stable update of https://github.com/RedHatInsights/insights-inventory-frontend/pull/1589
> [master-stable] Surface data collectors card to be used via fed modules (#1589)

- config/dev.webpack.config.js
- config/prod.webpack.config.js
Prod-beta update of https://github.com/RedHatInsights/insights-inventory-frontend/pull/1589
> [prod-beta] Surface data collectors card to be used via fed modules (#1589)

- config/dev.webpack.config.js
- config/prod.webpack.config.js
prod-stable update of https://github.com/RedHatInsights/insights-inventory-frontend/pull/1589
> [prod-stable] Surface data collectors card to be used via fed modules (#1589)

- src/components/InventoryTable/EntityTable.js
- src/components/InventoryTable/EntityTable.test.js
- src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
- src/components/InventoryTable/helpers.js
- src/store/entities.js
Resolves: [ESSNTL-3336](https://issues.redhat.com/browse/ESSNTL-3336)
Fixes the OS columns sorting by making the column key and sort key consistent system_profile. In case, they are different, sorting does not work and we need to provide operating.
> fix(ESSNTL-3336): fix os column sorting

- src/Utilities/TagsModal.js
- src/components/InventoryTable/EntityTableToolbar.js
fixes: https://issues.redhat.com/browse/ESSNTL-3427
Removes all impacting filters from the tags list in the tag filter.
> fix(Tags): show all tags for all systems

- src/Routes.js
- src/Utilities/constants.js
- src/api/api.js
- src/components/InventoryTable/EntityTableToolbar.js
- src/components/InventoryTable/InventoryTable.test.js
- src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
- src/components/filters/index.js
- src/components/filters/useRhcdFilter.js
- src/components/filters/useRhcdFilter.test.js
- src/routes/InventoryTable.js
Resolves: [ESSNTL-3580](https://issues.redhat.com/browse/ESSNTL-3580).
This PR introduces a new RHCD filter in the inventory list table. To test:
1. Visit the Inventory page
2. open the filters dropdown
3. Observe the new filter 'RHC status' added.
4. verify that it filters the table as expected
5. verify that URL param is added when the filter is active
6. verify that the filter is activated on load if it is present in the URL.
> feat(ESSNTL-3580): introduce rhc status filter

- .github/CODEOWNERS
This will ensure the team is notified with each new PR.
>  chore: Create CODEOWNERS [skip ci]

- src/components/InventoryGroups/Modals/DeleteGroupModal.cy.js
- src/components/InventoryGroups/Modals/DeleteGroupModal.js
- src/components/InventoryGroups/Modals/__tests__/CreateGroupModal.test.js
- src/components/InventoryGroups/Modals/__tests__/DeleteGroupModal.test.js
- src/components/InventoryGroups/utils/api.js
Delete group modal
https://issues.redhat.com/browse/ESSNTL-3736
> feat(inventory groups): delete group modal and tests

- config/setupTests.js
- src/Utilities/constants.js
- src/api/api.js
- src/components/InventoryTable/EntityTableToolbar.js
- src/components/InventoryTable/EntityTableToolbar.test.js
- src/components/InventoryTable/InventoryTable.test.js
- src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
- src/components/filters/index.js
- src/components/filters/useLastSeenFilter.js
- src/constants.js
- src/routes/InventoryTable.js
- src/store/inventory-actions.js
[ESSNTL-4056](https://issues.redhat.com/browse/ESSNTL-4056)
This PR implements a new date range filter in inventory. The mvp for the filter is as follows :
- User can use the "Last seen" filter to select a date range.
- If a start date is selected, "updated_start" should be added to the GET /hosts query.
- If an end date is selected, "updated_end" should be added to the GET /hosts query.
- If no value is selected for the filter, neither "updated_start" nor "updated_end" should be added to the GET /hosts query, and the host results should remain unchanged.
> feat(ESSNTL-4056): Add lastSeen filter

- src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
Will get back to this later ASAP. Temporarily removing the tests that caused CI and tests flakiness.
> chore: Temporarily comment an unstable test

- src/App.js
Relates to https://issues.redhat.com/browse/RHIF-125.
> chore: Stop calling deprecated chrome.init

- src/routes/InventoryDetail.js
- src/store/reducers.js
* fix(RHCLOUD-24793): Show ROS tab is azure or aws cloud provider
* Enable ros only for AWS
> [master-stable] fix(RHCLOUD-24793): Show ROS tab is azure or aws cloud provider (#1800)

- config/setupTests.js
- package-lock.json
- package.json
- src/routes/InventoryTable.test.js
Had to mock ``useChrome`` hook to be able to pass the test
> chore(deps): update frontend-components to 3.9.33

- src/routes/InventoryDetail.js
- src/store/reducers.js
* fix(RHCLOUD-24793): Show ROS tab is azure or aws cloud provider
* Enable ros only for AWS
> [prod-beta] fix(RHCLOUD-24793): Show ROS tab is azure or aws cloud provider (#1800)

- src/routes/InventoryDetail.js
- src/store/reducers.js
* fix(RHCLOUD-24793): Show ROS tab is azure or aws cloud provider
* Enable ros only for AWS
> [prod-stable] fix(RHCLOUD-24793): Show ROS tab is azure or aws cloud provider (#1800)

- src/Utilities/ChromeLoader.js
- src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
- src/components/InventoryGroupDetail/GroupDetailInfo.js
Fixes https://issues.redhat.com/browse/ESSNTL-4196.
This makes URLs in the group detail view dependent on `chrome.isBeta`: adds prefix /beta if the flag is true.
> fix(ESSNTL-4196): Tie URLs to chrome isBeta

- cypress/support/interceptors.js
- src/components/GroupSystems/GroupSystems.cy.js
- src/components/GroupSystems/GroupSystems.js
This addresses bugs found in https://issues.redhat.com/browse/ESSNTL-3727.
1. Go to /groups/%any_id view.
2. Check the Tags filter is present and works as expected.
3. Try to select the current page and go to another. The checkbox should not be filled because the second page is not selected.
4. Try to click on any system from the list and check that you are navigated to the host details page.
> fix(ESSNTL-3727): Fix minor issues for groups/%id view

- README.md
- config/dev.webpack.config.js
- config/spandx.config.js
- package-lock.json
- package.json
- src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
- src/components/InventoryGroupDetail/GroupDetailInfo.js
To test, you can run via /beta or /preview. We previously had issues with the local app being served. To ensure that it is properly being served, run the app via beta and make a change in the code or add a console log and ensure that you're getting local changes.
> chore(RHIF-222) Update /beta to /preview

- src/api/api.js
- src/components/filters/useLastSeenFilter.js
There were 2 more areas we needed to convert the api date data
> fix(lastSeen) update remaining filter data

- src/routes/InventoryDetail.js
- src/routes/InventoryTable.js
Renames the Inventory app pages to use the new title Systems.
> fix(RHIF-190): rename inventroy page title to Systems

- config/cypress.webpack.config.js
- config/overrideChrome.js
- cypress/fixtures/hosts.json
- cypress/support/commands.js
- cypress/support/component.js
- src/components/GroupSystems/GroupSystems.cy.js
- src/components/InventoryTable/InventoryTable.cy.js
No jira required.
This sets up infrastructure (mount functions, mocked data) for InventoryTable tests with cypress.
> test: Implement basic cypress tests suite for InventoryTable 

- src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
Fixes https://issues.redhat.com/browse/ESSNTL-3730.
When adding a host to a newly created group, there can be some back-end latency. Thus, new groups (in rare cases) can be not shown in the refreshed list (https://issues.redhat.com/secure/attachment/12968904/2023-05-15%2009-26-02.mp4). This implements a small delay (500 ms) for GET /groups request in the "add host to group" modal.
1. Go to https://stage.foo.redhat.com:1337/preview/insights/inventory
2. Select any host and click "Add to group"
3. Click "Create new group", and try to create a new group with any name
4. Once redirected back to the host addition modal, check that the request to GET /groups is not sent immediately but with delay.
> fix(ESSNTL-3730): Add delay before fetching groups again

- config/overrideChrome.js
- cypress/fixtures/edgeSystemProfile.json
- cypress/fixtures/hostDetail.json
- cypress/support/commands.js
- cypress/support/interceptors.js
- src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
- src/components/GroupSystems/GroupSystems.cy.js
- src/components/GroupsTable/GroupsTable.cy.js
- src/components/InventoryDetail/ApplicationDetails.js
- src/components/InventoryDetail/InventoryDetail.js
- src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
- src/components/InventoryGroups/InventoryGroups.cy.js
- src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
- src/components/InventoryGroups/Modals/CreateGroupModal.cy.js
- src/components/InventoryGroups/Modals/DeleteGroupModal.cy.js
- src/components/InventoryGroups/Modals/RenameGroupModal.cy.js
- src/components/InventoryTable/InventoryTable.cy.js
- src/components/SystemDetails/Vulnerability.js
- src/components/VulnerabilityEdgePrompt.js
- src/routes/InventoryDetail.cy.js
- src/routes/InventoryDetail.js
Resolves: https://issues.redhat.com/browse/ESSNTL-3577
To test:
1. Go to Inventory table
2. Filter systems bay System Update method = rpm-ostree
3. open one of the systems filtered
4. verify that Patch, compliance tabs are disabled
5. Verify that on Vulnerability tab, a new design is shown according to the [mock](https://www.sketch.com/s/60a21d8c-d9c1-4c19-9011-460dd0d157de) and leads to Edge system detail page on button click
> feat(ESSNTL-3577): hide non-edge tabs

- config/overrideChrome.js
- cypress/fixtures/hostsTags.json
- cypress/fixtures/tags.json
- cypress/support/commands.js
- src/components/InventoryGroups/Modals/AddHostToGroupModal.cy.js
- src/components/InventoryGroups/Modals/AddHostToGroupModal.js
- src/components/InventoryGroups/Modals/RemoveHostsFromGroupModal.js
- src/components/InventoryGroups/utils/api.js
- src/components/InventoryTable/InventoryTable.cy.js
- src/routes/InventoryTable.cy.js
- src/routes/InventoryTable.js
- src/routes/InventoryTable.test.js
Fix for the https://github.com/RedHatInsights/insights-inventory-frontend/pull/1866 after resolving merge conflicts
> Remove from group

- cypress/fixtures/groups.json
- cypress/fixtures/groups/620f9ae75A8F6b83d78F3B55Af1c4b2C.json
- cypress/fixtures/groupsSecondPage.json
- cypress/support/interceptors.js
- src/__mocks__/mockedGroups.json
- src/components/GroupSystems/GroupSystems.js
- src/components/GroupSystems/index.js
- src/components/GroupsTable/GroupsTable.js
- src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
- src/components/InventoryGroups/Modals/CreateGroupModal.cy.js
- src/components/InventoryGroups/utils/api.js
(no jira)
This polishes some of the components and ensures tables read right data from responses according to https://console.stage.redhat.com/docs/api/inventory/v1.
1. Navigate to /groups with `insights-qa`
2. Make sure all data is rendered correctly: columns have valid data. Verify sorting, filtering, pagination.
3. Go to any group with/without hosts, make sure there are no new visible bugs, data is rendered correctly, if group has hosts, then all these hosts are shown in the table.
> fix(Groups): Fix incorrect API keys resolution

- src/components/InventoryTable/EntityTable.js
- src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
- src/components/InventoryTable/__snapshots__/InventoryList.test.js.snap
This just adds the hj suppress class to inventory table imported by other apps. Obfuscates the rows/ updates snapshots
> chore(RHIF-104): Add obfuscating class for hj and sentry

- package-lock.json
- src/routes/InventoryDetail.js
Fixes issue where Inventory does not display ROS tab correctly based on the cloud provider.
> ESSNTL-4883 - ROS tab not visible in Inventory fix

- package-lock.json
- package.json
There is currently an issue with broken hash values used to reference the build files, this causes the application not to load. This PR fixes such issue by using newest version of frontend components config which uses correct hash values.
> Update components config to latest version

- src/components/InventoryGroups/InventoryGroups.cy.js
- src/components/InventoryGroups/InventoryGroups.js
- src/routes/InventoryGroups.js
- src/routes/InventoryGroups.test.js
Implements https://issues.redhat.com/browse/ESSNTL-4934.
The app must check if user has the minimum required permission (`inventory:groups:read`) to access the /inventory/groups list.
> feat(ESSNTL-4934): Require read permissions to access the groups list

- src/components/GroupsTable/GroupsTable.js
- src/components/InventoryTable/helpers.js
No jira. **Has to be merged, not squashed.**
1. Go to /groups
2. Check that when loading, there are checkboxes disabled, and the columns' widths are not changed,
3. Check that there is no "No results" message between the loading state and the state when the rows (groups) are loaded and rendered (you have to have at least one group created),
> Groups table minor enhancements

- src/Routes.js
Adds zero state to inventory
Run inventory on an account with 0 systems and run inventory with
ENVIORNMENT=prod npm run start:proxy:beta
> feat(RHIF-254) Add Zero State to Inventory

- src/components/GeneralInfo/ConfigurationCard/__snapshots__/ConfigurationCard.test.js.snap
- src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
- src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
- src/components/GeneralInfo/LoadingCard/LoadingCard.js
- src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
Fixed [React router v6 migration regression.](https://github.com/RedHatInsights/insights-inventory-frontend/pull/1968/files#diff-f57286f910df2dbef6fc8aea8786bd47976982b4a6cec3184c96244e46db2f59R113)
> Fix Clickable component displaying additional text

- src/Utilities/hooks/useBulkSelectConfig.js
- src/components/GroupSystems/GroupSystems.cy.js
- src/components/GroupSystems/GroupSystems.js
- src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
- src/routes/InventoryTable.js
[ESSNTL-4485](https://issues.redhat.com/browse/ESSNTL-4485)
This implements Select All option in Groups detail page and "Add Systems" modal inside the Groups detail
Merged the implementation of Group bulk select and Inventory bulk select, so Inventory bulk select has to be verified as well.
How to test:
1. Make sure correct amount gets added when you Add a system / deleted when you remove systems.
2. Make sure selection still behaves correctly in Inventory systems with and without applied filters.
> feat(ESSNTL-4485): Add Select All in Groups detail, Add systems modal

- src/components/InventoryDetail/DetailRenderer.js
Fixes https://issues.redhat.com/browse/ESSNTL-5292.
The `DetailRenderer` component was using too strict minimum permissions for viewing hosts. This resulted in some of the federated modules from Inventory not being accessible: if you had group-level hosts access, then you will be restricted from viewing host details, for example, in Compliance system details.
This PR enhances the component and makes it fetch the group if the host is a member of any, and only then verify required permissions.
Try to reproduce the steps (in Compliance) from the related bug ticket. With group-level access to hosts, you should see Compliance loading system header successfully.
> fix(ESSNTL-5292): Correct minimum host permissions

- src/api/edge/imagesInfo.js
- src/components/VulnerabilityEdgeAlert.js
- src/components/VulnerabilityEdgePrompt.js
- src/routes/InventoryDetail.cy.js
[THEEDGE-3524](https://issues.redhat.com/browse/THEEDGE-3524) insert vulnerability details for edge devices and enabling update action
> feat(THEEDGE-3524) Include list of vulnerabilities and action based on image Set for device

- src/Utilities/OperatingSystemFormatter.js
- src/Utilities/OperatingSystemFormatter.test.js
https://issues.redhat.com/browse/HMS-2648
> fix(HMS-2648): Show the OS major minor version for CentOS systems

- config/overrideChrome.js
- cypress/support/interceptors.js
- src/routes/InventoryDetail.cy.js
- src/routes/InventoryDetail.js
- src/routes/SystemUpdate.js
Add missing update action button to edge systems.
[THEEDGE-3564](https://issues.redhat.com/browse/THEEDGE-3564)
> fix(THEEDGE-3564): Add missing update action button to edge systems

- src/components/VulnerabilityEdgePrompt.js
Change the link from customer portal to vulnerability cve
> feat(THEEDGE-3598): remove link to customer portal and redirect to cve page

- src/routes/InventoryTable.js
Resolves: https://issues.redhat.com/browse/ESSNTL-5490
Pass props down to tabs.
> fix(RHIF-313): fix not seeding url param page in Inventory page

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- src/components/ImmutableDevices/ImmutableDevices.js
- src/components/ImmutableDevices/Status.js
- src/components/ImmutableDevices/helpers.js
- src/components/ImmutableDevices/statusMapper.js
This is the new table component that is shared through the fed-mod. It can be further extended and used to show an Immutable device table.
> feat(RHIF-279: configurable, shared ImmutableDevices table

- cypress/support/interceptors.js
- src/components/InventoryTabs/HybridInventoryTabs.cy.js
- src/components/InventoryTabs/HybridInventoryTabs.js
Adds component tests for HybridInventoryTabs
> chore(RHIF-277): add cypress rest coverages

- .travis.yml
- README.md
Enable commitlint in all branches.
> chore(commitlint): Enable commitlint on all branches

- config/dev.webpack.config.js
- config/prod.webpack.config.js
- src/components/ImmutableDevices/ImmutableDevices.js
- src/components/ImmutableDevices/Status.js
- src/components/ImmutableDevices/columns.js
- src/components/ImmutableDevices/helpers.js
- src/components/ImmutableDevices/index.js
- src/components/ImmutableDevices/statusMapper.js
- src/modules/ImmutableDevices.js
This reverts commit 6a41a4ca25086398491f7388a69d7f854cca3880
Yesterday, there were issues with merged commits and I reverted 2 of them for a fast EE deployments fix. I am bringing them back today, will merge this after all checks pass
> feat(RHIF-279): configurable, shared ImmutableDevices table

- README.md
> chore(README): announce containers migration

- src/components/InventoryHostStaleness/HostStalenessCard.js
- src/components/InventoryHostStaleness/TabCard.js
Add OUIA ids for custom staleness buttons:
Edit
Reset to default setting
> fix(OUIA): Add OUIA ids for custom staleness buttons

- src/components/InventoryHostStaleness/HostStalenessCard.js
> fix(ESSNTL-5537): Implement ouiaId but edit button

- src/components/ImmutableDevices/columns.js
Disables sorting on Status column in immutable devices table
> fix(RHIF-294): disable sorting on immutable status column

- src/components/ImmutableDevices/ImmutableDevices.cy.js
- src/components/ImmutableDevices/ImmutableDevices.js
Covers new fed-mod Immutable devices with cypress tests
> chore(ImmutableDevices): cover with cypress tests

- src/components/ImmutableDevices/ImmutableDevices.cy.js
- src/components/ImmutableDevices/ImmutableDevices.js
This adds extra props to the ImmutableDevices module to make it more usable. Cypress tests are added.
> chore(ImmutableDevices): add extra props to immutable table

- README.md
- config/dev.webpack.config.js
- config/spandx.config.js
- package-lock.json
- package.json
- src/components/InventoryTable/EntityTable.js
- src/store/entities.js
Implements https://issues.redhat.com/browse/RHINENG-1658, https://issues.redhat.com/browse/RHINENG-2694.
This enables sorting by the Group column at /inventory (the main systems view) and /groups/%id (the group details view, the Add systems modal).
1. At /inventory and /groups/%id, verify that you are able to sort hosts by groups correctly in ascending and descending orders.
> feat(RHINENG-1658): Sort by group column

- cypress/support/interceptors.js
- src/Routes.js
- src/Routes.test.js
- src/components/ImmutableDevices/ImmutableDevices.js
- src/components/InventoryTable/EntityTable.test.js
- src/components/InventoryTable/EntityTableToolbar.js
- src/components/InventoryTable/InventoryTable.test.js
- src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
- src/components/InventoryTable/hooks/useColumns.js
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
- src/components/InventoryTabs/ConventionalSystems/useTableActions.js
- src/components/filters/useGroupFilter.js
- src/store/entities.js
Implements https://issues.redhat.com/browse/RHINENG-2801.
> chore(RHINENG-2801): Stop using inventory groups feature flag

- README.md
* This PR comes to address common installation problems that user might encounter when they first install our application or update to the latest version
* This is just a suggestion of course, in case someone sees a better way to write this is more then welcome to suggest it or add another common problem that might be useful to mention in this section 😇 
1. After a conversation with @mkholjuraev, we thought a README update might be needed with the case I mentioned in the first commit
2. The second commit fixes typos that were in the README in 'Release process change in stage env' section
> Chore: Update README With 'Common Problems Users Might Encounter' Section

- src/routes/InventoryDetail.js
RHINENG-7656 fixed ros tab missing in inventory details page
Jira: https://issues.redhat.com/browse/RHINENG-7656
> RHINENG-7656 fixed ros tab missing in inventory details page

- src/components/InventoryGroupDetail/InventoryGroupDetail.js
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
- src/routes/InventoryGroups.js
- src/routes/InventoryHostStaleness.js
- src/routes/SystemUpdate.js
Resolves: https://issues.redhat.com/browse/RHINENG-9387
Updates page titles according to 'Current concept' column, single line treatment in this [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)
> chore(RHINENG-9387): update page titles

- src/routes/InventoryComponents/InventoryPageHeader.js
Add "View by" text to the left of system table toggle on the Systems table page header. Each toggle button should have tooltips.
> feat(RHINENG-9686): Add system table toggle details

- src/components/InventoryGroupDetail/InventoryGroupDetail.js
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
- src/routes/InventoryGroups.js
- src/routes/InventoryHostStaleness.js
- src/routes/SystemUpdate.js
This fixes the page title for Staleness and Deletion page according to the comments in [RHINENG-9387](https://issues.redhat.com/browse/RHINENG-9387)
> chore: fix staleness page title

- doc/props_detail.md
- src/Utilities/DeleteModal.js
- src/Utilities/__snapshots__/DeleteModal.test.js.snap
- src/components/InventoryDetail/TopBar.js
- src/components/InventoryDetail/TopBar.test.js
- src/components/InventoryGroups/Modals/__tests__/RemoveHostsFromGroupModal.test.js
- src/components/InventoryHostStaleness/HostStalenessCard.js
- src/components/InventoryHostStaleness/constants.js
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.test.js
- src/components/InventoryTabs/ConventionalSystems/useTableActions.js
- src/routes/InventoryComponents/HybridInventory.cy.js
- src/routes/InventoryDetail.cy.js
- src/routes/InventoryHostStaleness.js
- src/store/actions.js
- src/store/inventory-actions.js
Reverts RedHatInsights/insights-inventory-frontend#2195
> Revert "System "removal" instead of "deletion""

- src/Utilities/DeleteModal.js
- src/Utilities/DeleteModal.test.js
- src/Utilities/__snapshots__/DeleteModal.test.js.snap
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.test.js
- src/routes/InventoryComponents/HybridInventory.cy.js
https://issues.redhat.com/browse/RHINENG-5276
> fix(RHINENG-5276): Change 'Remove' to 'Delete' in Delete system modal

- src/components/InventoryHostStaleness/constants.js
> fix: Typo in custom staleness options

- src/components/GeneralInfo/GeneralInformation/ConversionAlert.js
- src/components/InventoryTable/ConversionPopover/ConversionPopover.js
> fix(ConversionAlert): Change the alert text about EOL

- src/components/InventoryHostStaleness/constants.js
> fix: Quick typo fix in the staleness component

- README.md
- src/Utilities/path.js
- src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
- src/components/InventoryGroupDetail/GroupDetailInfo.js
Fixes https://issues.redhat.com/browse/RHINENG-10786.
> fix(RHINENG-10786): Remove occurrence of /preview

- src/components/GroupsTable/GroupsTable.cy.js
> chore: Remove .only from GroupsTable.cy.js test

- config/setupTests.js
- src/components/InventoryTable/EntityTableToolbar.js
- src/components/InventoryTable/EntityTableToolbar.test.js
- src/components/InventoryTable/InventoryTable.js
- src/components/InventoryTable/hooks/useInventoryExport.js
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
- src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.test.js
- src/store/inventory-actions.js
This implements the submission of an export request to the Export service if enabled.
1) Open the Systems page (ensure the `hbi.export-data` is enabled)
2) Select some filters
3) Try to export
4) Verify that a Request was submitted to the Export API and a notification was triggered according to the UX mocks.
> feat(InventoryTable): RHINENG-9871 - Implement systems export

- src/Utilities/InsightsDisconnected.js
Resolves: https://issues.redhat.com/browse/RHINENG-11787
Just replace the Registration Assistant text with Register Systems according to the ticket requirement
> fix(RHINENG-11787): change Registration assistant to Register systems

- .travis.yml
This PR makes inventory consistent with other apps when it comes to how commit lint is run. With this change, commit lint is run for all commits on master and also for all pull requests commits.
> chore: do run commit-lint in both master and pull requests

- src/store/actions.js
- src/store/actions.test.js
https://issues.redhat.com/browse/RHINENG-4797
> fix(notification): Update notification text when updating display name

- babel.config.js
- package-lock.json
- package.json
- src/api/api.js
> chore: Remove unused dependencies

- src/components/GeneralInfo/BiosCard/BiosCard.js
- src/components/GeneralInfo/BiosCard/__snapshots__/BiosCard.test.js.snap
- src/components/GeneralInfo/BootcImageCard/BootcImageCard.js
- src/components/GeneralInfo/BootcImageCard/__snapshots__/BootcImageCard.test.js.snap
- src/components/GeneralInfo/CollectionCard/CollectionCard.js
- src/components/GeneralInfo/CollectionCard/__snapshots__/CollectionCard.test.js.snap
- src/components/GeneralInfo/ConfigurationCard/ConfigurationCard.js
- src/components/GeneralInfo/ConfigurationCard/__snapshots__/ConfigurationCard.test.js.snap
- src/components/GeneralInfo/DataCollectorsCard/DataCollectorsCard.js
- src/components/GeneralInfo/DataCollectorsCard/__snapshots__/DataCollectorsCard.test.js.snap
- src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
- src/components/GeneralInfo/InfrastructureCard/InfrastructureCard.js
- src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
- src/components/GeneralInfo/LoadingCard/LoadingCard.js
- src/components/GeneralInfo/LoadingCard/index.js
- src/components/GeneralInfo/OperatingSystemCard/OperatingSystemCard.js
- src/components/GeneralInfo/SubscriptionCard/SubscriptionCard.js
- src/components/GeneralInfo/SubscriptionCard/__snapshots__/SubscriptionCard.test.js.snap
- src/components/GeneralInfo/SystemCard/SystemCard.js
- src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.js
- src/components/GeneralInfo/SystemStatusCard/__snapshots__/SystemStatusCard.test.js.snap
https://issues.redhat.com/browse/RHINENG-13533
just ads unique ids to all the inventory details cards.
> chore(RHINENG-13533): Give details cards unique ids

- package-lock.json
- package.json
[RHINENG-11998](https://issues.redhat.com/browse/RHINENG-11998)
Minimal verions of the packages to be updated:
@redhat-cloud-services/ frontend-components-config@6.2.3
@redhat-cloud-services/ frontend-components-config-utilities@3.2.2
> chore(deps): bump frontend-components-config

- src/Utilities/TagsModal.js
Fix issue mentioned in:
https://issues.redhat.com/browse/RHINENG-12940
The width of modal used to change when changing pages/clicking checkboxes etc.
> fix(Tag modal): Fix Tag modal width flickering

- src/routes/InventoryComponents/InventoryPageHeader.js
- src/routes/InventoryComponents/InventoryPopover.js
This adds a popover to the Systems Title on systems page pr : https://issues.redhat.com/browse/RHINENG-12428
> feat(RHINENG-12428): Add Systems Page Popover

- src/components/InventoryGroups/SmallComponents/Popover.js
- src/routes/InventoryComponents/InventoryPageHeader.js
- src/routes/InventoryComponents/InventoryPopover.js
Fix items order
Before:
After:
> fix(RHINENG-12428): Make header look correct

- src/Utilities/constants.js
- src/components/GeneralInfo/DataCollectorsCard/__snapshots__/DataCollectorsCard.test.js.snap
- src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
To test, go to system details and view the Data collectors card. Expand the `insights-client` and `subscription-manager` rows to see the updated content.
> fix(RHINENG-12952): Capitalize Data Collectors text

- .tekton/host-inventory-frontend-pull-request.yaml
> add missing workspaces into host-inventory-frontend-pull-request.yaml - fix clone-repository task

- src/components/InventoryTable/InventoryList.js
- src/store/inventory-actions.js
[RHINENG-15644](https://issues.redhat.com/browse/RHINENG-15644)
Go to Workspaces > Any workspace that has some systems, ideally on both tables
Make sure the table loads and you're able to sort/paginate etc.
> fix(RHINENG-15644): sorting

- .eslintignore
- .eslintrc.js
- fec.config.js
- src/Utilities/OperatingSystemFilterHelpers.js
- src/Utilities/URLSearchParams.js
- src/components/InventoryDetail/AppInfo.js
- src/components/InventoryDetail/ApplicationDetails.js
- src/components/InventoryDetail/FactsInfo.js
- src/components/InventoryDetail/InventoryDetail.js
- src/components/InventoryDetail/SystemNotFound.js
- src/components/InventoryDetail/TopBar.js
- src/components/InventoryTable/EntityTable.js
- src/components/InventoryTable/EntityTableToolbar.js
- src/components/InventoryTable/InventoryList.js
- src/components/InventoryTable/InventoryTable.js
- src/components/InventoryTable/NoEntitiesFound.js
- src/components/InventoryTable/Pagination.js
- src/components/InventoryTable/TitleColumn.js
- src/components/InventoryTable/hooks/useInventoryExport/useExportDownloadCheck.js
- src/components/InventoryTable/hooks/useInventoryExport/useInventoryExport.js
- src/modules/OsFilterHelpers.js
This fixes the errors that are triggered when running the JSDoc pipeline on master. Also it adds eslint rules that helps align the documentation comments.
> fix: Fix JSDoc errors, add eslint rules

- src/components/InventoryDetail/DetailHeader.js
- src/components/InventoryDetail/OsModeLabel.js
- src/components/InventoryDetail/OsModeLabel.test.js
> feat(RHINENG-15172): add OS mode to system detail

- .gitmodules
- .tekton/host-inventory-frontend-pull-request.yaml
- .tekton/host-inventory-frontend-push.yaml
[RHINENG-16155](https://issues.redhat.com/browse/RHINENG-16155)
> chore(build): use shared Dockerfile

- src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
- src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.js
- src/components/GeneralInfo/SystemStatusCard/__snapshots__/SystemStatusCard.test.js.snap
> fix(RHINENG-11372): Change Last upload to Last seen on System Details page

- src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
- src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.js
- src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.test.js
- src/components/GeneralInfo/SystemStatusCard/__snapshots__/SystemStatusCard.test.js.snap
Added Last updated field to System details -> System status card with data from `/host/:id` updated field
Last seen now displays most recent upload from reporters
> feat(SystemStatus): add Last updated field to card

- src/components/GeneralInfo/InfoTable/InfoTable.js
This PR recreates the InfoTable component as a functional component.
> fix(RHINENG-17344): Convert class component InfoTable into functional one

- src/Utilities/LastSeenColumnHeader.js
- src/store/entities.js
https://issues.redhat.com/browse/RHINENG-15545
> feat(RHINENG-15545): Add tooltip to Last seen column

- src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
- src/components/GeneralInfo/InfoTable/InfoTable.js
This PR converts the GeneralInformation component used to display various cards on System's Details page to the functioinal one.
To verify this change - go to System's Details page and verify that all cards (System properties, Infrasctructure, System status etc...) are displayed correctly and its functionalities remained the same (user can open modals, click on links etc...).
> feat(RHINENG-17382): Convert class component GeneralInformation into functional one

- src/routes/InventoryComponents/InventoryPopover.js
https://issues.redhat.com/browse/RHINENG-17021
Add new text paragraph and link. Removed component prop from other paragraphs as `TextVariants.p` is the default value.
> feat: Add information about notifications into Inventory header popover RHINENG-17021
