RedHatInsights/insights-inventory-frontend

config/spandx.config.js

It's probably not a good idea to keep the CI inventory URL out in the open, so that it may not be abused

Remove inventory CI URL

---

.travis/custom_release.sh

* on `master` it will automatically release to `ci-beta` and `qa-beta`
* on `master-stable` it will automatically release to `ci-stable` and `qa-stable`
* on any other branch listed as build branch it will automatically push to this branch as a way how to promote specific env

Improve build to release automatically to beta

---

src/components/inventory/Compliance.js
src/store/reducers.js

Fixed Compliance tab problem with missing react intl provider so it will not throw arror when rendered.

Add react intl to compliance tab

---

package-lock.json
package.json

Notice this is going to prod-beta, it should probably be cherry-picked to any QA env where the 0.0.34 or higher is used. 
The changes in the API in:
https://github.com/RedHatInsights/frontend-components/commit/a2a009a2ddccc004f044473887dcbcf8b717516b#diff-dbd2a0d59c0484c28f333a4bc8891abd 
are only available in CI, but not in QA, prod.., so using the 0.0.36 version will result in the whole page not being able to render as GQL won't respond with these fields.

Downgrade inventory-compliance to 0.0.33 to support current prod-API

---

package-lock.json
package.json

We still need to promote certain changes to QA in order to support higher versions of inventory-compliance. Only CI is kept up to date currently, please do not upgrade inventory-compliance yet, until we give the OK.

Downgrade inventory-compliance to 0.0.33 to support current QA API

---

package-lock.json
package.json
src/App.js
src/components/PermissionsLoader.js
src/components/PermissionsLoader.test.js
src/components/inventory/GeneralInfo.js
src/constants.js
src/hooks/useInventoryWritePermissions.js
src/routes/InventoryDetail.js
src/routes/InventoryTable.js
src/store/permissions/reducer.js
src/store/permissions/reducer.test.js
src/store/reducers.js

closes https://issues.redhat.com/browse/RHCLOUD-9754
**Description**
If not on prod, the `PermissionLoader` component will load up `writePermissions` to redux. `InventoryTable` and `InventoryDetail` are not shown until the permissions are loaded (to prevent pop-in). Also, `writePermissions` are passed to `InventoryDetail` > `SystemCard` to also prevent pop-in and to not load permission multiple times.
**TODO**

Move permissions to redux

---

src/App.js
src/hooks/useInventoryWritePermissions.js
src/store/permissions/reducer.js
src/store/permissions/reducer.test.js

Since we are enabling RBAC for profuction no need to have RBAC gated behind `isProd` flag from chrome.

Enable RBAC everywhere

---

src/Utilities/constants.js
src/Utilities/constants.test.js
src/routes/InventoryTable.js

if user navigates to inventory default filters are not stored in URL, this causes an error with sorting and user is not able to save partial filters in URL. This PR fixes such issue by computing active filters on load and if no filters (`undefined`! Not empty array) are passed from inventory it will use default filters as fallback.

Apply default filters on page load

---

src/routes/InventoryTable.js

While changing filters they can be wrongly generated under certain scenarios, like clearing out all filters and applying just filter by name. This PR fixes such issue by using same logic as for generating the filters in URL.
Fixes: RHCLOUD-10465

Use same filter generator as on load

---

src/store/reducers.js

When user types in URL some strange page or pagination it can break the UI. There is even report that user can somehow enter this state trough selecting systems. This PR fixes such issue by using default values when NaN is passed in the URL.

Use default values for pagination

---

src/routes/InventoryTable.js
src/routes/InventoryTable.test.js

When user removes some system it populates the url with `undefined` values, this is not correct as it can break the UI. This PR fixes such issue, by either using old values if no `page` or `per_page` is added or even if these values are not present do not set them at all.

Fix pagination not to accept undefined

---

src/routes/InventoryTable.js

`onRefreshUpdate` is called before the state is updated, but we need to update the props first and then call the `onRefreshUpdate`. We could also call the `onRefreshUpdate` with the correct options, however, I think it's better to let the inventoryTable handle it.
**Before**
**After**

Call onRefreshData after render cycle to get the latest props

---

src/routes/InventoryDetail.js

Customer is using the RHEL cockpit web console(http://example.com:9090/system) to access the insights host.
- Go to http://127.0.0.1:9090/system
- Under "Health" tile, Click on hyperlink "Insights:1 moderate hit"
- It will redirect user to the wrong url "https://cloud.redhat.com/insights/inventory/xx-xxx-xxx/insights" which results into this error.
Cockpit is incorrectly linking to this page and adding an additional `/insights` at the end. They're a shipped product so it could take a bit before this is fixed on their end.
BZ will be updated when made.

Fix cockpit linking to wrong page in inventory

---

src/components/DeleteModal.js
src/components/inventory/GeneralInfo/SystemCard/SystemCard.js
src/components/inventory/GeneralInfo/TextInputModal/TextInputModal.js

Extended OUIA ids in delete modal, and added some optional parameters for TextInputModal so that OUIA ID's can be optionally inserted and added them to edit modals in inventory.
cc @karelhala

extend OUIA IDs in delete/edit modals

---

config/dev.webpack.config.js
package-lock.json
package.json

closes #1346
Node 16 failed to install dependencies because of nested node-sass
packages which is no longer supported. New version of the cloud services
config does not include this dependency anymore.

Update webpack dependencies

---

src/components/InventoryDetail/AppInfo.js
src/components/InventoryDetail/InventoryDetail.js
src/components/InventoryDetail/helpers.js
src/routes/InventoryDetail.js

jira: https://issues.redhat.com/browse/RHCLOUD-12979
- remove default prop for `onBackToListClick`
- add an additional check for the back to the previous page to choose the correct URL.
@karelhala I've also noticed that the tabs are still trying to render when the system is not found. As it is passed as a child to the detail wrapper, it should be handled from the parent component. ~~Could you point me in~~ Found it.

Fix Back to previous page button in empty state.

---

package-lock.json
src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap
src/store/entities.js
src/store/inventory-actions.js
src/store/reducers.js
src/store/reducers.test.js

When changing filters during loading, filters are not being updated - because useEffect hooks are disabled when `loaded` is false.
I removed this condition and make a new condition in reducer so only the latest request will rewrite the store. This means that there can be multiple requests at the same time, but only the latest will change the state.
**Before** (notice the different total)
**After**
cc @leSamo

Use only the latest request to reload state

---

src/Utilities/OperatingSystemFormatter.js
src/Utilities/OperatingSystemFormatter.test.js
src/__mocks__/selectors.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/OperatingSystemCard/OperatingSystemCard.js
src/components/GeneralInfo/OperatingSystemCard/__snapshots__/OperatingSystemCard.test.js.snap
src/components/GeneralInfo/selectors/selectors.js
src/components/GeneralInfo/selectors/selectors.test.js
src/store/entities.js

This addresses two issues:
- [ESSNTL-1725](https://issues.redhat.com/browse/ESSNTL-1725): When the operating_system's minor version is set to 0, it won't display "RHEL 8.0", for instance; it will just say "RHEL". That's because the component does not differentiate between falsy values.
- [ESSNTL-1717](https://issues.redhat.com/browse/ESSNTL-1717): The "Release" field on the host detail page uses the deprecated system_profile.os_version field, instead of system_profile.operating_system.
I was going to make separate PRs for these, but they ended up being too tightly coupled. I refactored a bit so that we could reuse `OperatingSystemFormatter`; this added a `<span>` around the Release value, so I had to update the snapshots as well. There isn't isn't a visible change in the formatting, …

Fixes for operating_system's display issues

---

doc/inventory_header.md

The path takes you to a 404 right now. I assume the directory structure used to be different. Updating to take you to what I presume is the correct doc.

Fix path to inventory.md doc in inventory_header.md

---

src/Utilities/constants.js
src/api/api.js
src/api/tagsApi.test.js
src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
src/components/filters/useRegisteredWithFilter.test.js

This PR is intented to enable filtering hosts withour insights client  connection. 
To test locally:
1. Open inventory list table.
2. Use filters dropdown and click on 'Source' filter and choose 'Insights not connected.
3. You should expect that the table is not broke.
There is a bug in the APi thus the request is not getting correct result. The Inventory engine team told me that I can make a request with the syntax: `api/inventory/v1/hosts?filter[system_profile][insights_client_version]=nil` and they will fix the bug . So the improtant thing to test is that the request syntax is correct.

ESSNTL-8: ability to filter w/o Insights (needs test)

---

src/api/api.js

Intended to fix `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')` error in Drift app.

chore: handle undefined registeredWithFilter

---

src/components/InventoryTable/EntityTable.js
src/components/InventoryTable/InventoryList.scss
src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
src/components/InventoryTable/__snapshots__/InventoryList.test.js.snap

Request was to change the table to compact version. I've centered the content as well.
In my opinion the name should be a bit smaller maybe md or even sm. Open for changes.
Before:
After:

fix(ESSNTL-2194) Use compact table

---

src/api/api.js

This fix the issue with the tags in the dropdown for the filter not being filtered properly when searching with the "Name" filter in the `InventoryTable`.

fix(API): ESSNTL-1392 - Include hostnameOrId to filter tags

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/helpers.js
src/store/entities.js

With this change, when clicking 'Reset Filters' button in the inventory table, the filter chips go back to the default filters of **status fresh** and **stale**, and the URL reflects that.
To see changes navigate to inventory page, 
Add a filter (or remove one)
Press the reset filter button
The default filters are restored, and the URL will reflect the parameters

ESSNTL-2257

---

src/Utilities/constants.js
src/components/InventoryDetail/InsightsPrompt.js
src/components/InventoryTable/InventoryTable.test.js
src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
src/components/filters/useRegisteredWithFilter.js
src/components/filters/useRegisteredWithFilter.test.js

This addresses [ESSNTL-2449](https://issues.redhat.com/browse/ESSNTL-2449), using the information decided upon by [ESSNTL-2443](https://issues.redhat.com/browse/ESSNTL-2443).
This renames "Source" to "Data Collector", and adds more options to the list. Here is the association of data collectors to reporters:
- insights-client -> puptoo
- subscription-manager -> rhsm-conduit
- Satellite/Discovery -> yupana

Rename Source filter; add data collector options

---

src/store/entities.js

Fixes [ESSNTL-2777](https://issues.redhat.com/browse/ESSNTL-2777).
For mobile view OS column did not have the correct label.
Before:
After:

Add data label to OS column

---

src/routes/InventoryTable.js

This fixes this issue:
However, I am not 100% sure what was/is happening. The `loading` was for RBAC permissions and the RenderWrapper is also requesting RBAC permissions. So, there must be a connection there, but I don't know how or what.

fix(InventoryTable): Mount the component to allow state updates

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap
src/routes/InventoryTable.js

Reset Filters button is now always present. When adding an osFilter , if you then remove another filter behind it, it does not change the url to display operating system three times with arguments 0,1,2. 
To replicate first fix, 
- Navigate to inventory
- deselect all filters 
- Reset Filter button is still present, where before it was not
To replicate second fix
- Navigate to inventory
- Choose osFilter , 8.0 , 9.0 , whichever you like
- remove fresh and stale filters
- You'll see the url is valid, and filters are working properly
- Remove all filters, you'll see that reset filter button is still present, and if you select it you're back to default filters

Fix for ESSNTL-2787

---

src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap
src/routes/InventoryTable.js

In PR 2782, I updated the wrong InventoryTable (there are 3). This PR reverts the hard coding of ShowDeleteButton in an inventory table that gets imported, and hard codes it in the one just for this repo. The reset Filter Button is to always be present as per UI/UX. In inventory the Reset Filter button should always be present with this PR.
To see if it affects another Repo, you can run something like advisor or vulnerability via` npm run start:proxy:beta -- --port=8004` and run inventory with something like `LOCAL_API=vulnerability:8004~https npm run start:proxy`.

Fix hardcoding changes from 2787

---

src/AppEntry.js

When passing `undefined` in non-dev environments, it would raise an error, as it expects a middleware function.

fix(AppEntry): Calling init with undefined causes an error in non-dev

---

src/Routes.js

The custom `checkPaths` appears to have stopped working correctly and cause an unintended redirect to the root on details pages under `/beta`.
Using the `Redirect` still preserves the redirect to the root when no matching route is found, but does not cause unintended redirects on `/beta` details pages.

fix(Routes): Use proper react-router Redirect

---

package-lock.json
package.json
src/api/api.js

Since there were a few new features added to the JS client we should update to the latest one. This PR uses the newest version 1.0.110 and updates all changed requests based on the docs generated from the openapi spec.

Update JS client to newest version 1.0.110

---

src/components/InventoryTable/EntityTable.js
src/components/InventoryTable/EntityTable.test.js
src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
src/components/InventoryTable/helpers.js
src/store/entities.js

This reverts commit ff9be46e3a7f31289eeb1d31e99fb52c93ffc292. Also fixes the bug by handing this specific sort key by getting its index explicitly in the codebase. Please verify that it works by running locally.

Revert "fix(ESSNTL-3336): fix os column sorting"

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap

I have recently identified that InventoryTable has a "filters" parameter which is not utilized by the components nor any of the children components. I propose to remove this from the propTypes - a tiny contribution to reduce the components complexity/misleading interface.

chore(InventoryTable): remove unused filters param

---

src/__mocks__/mockedData.json
src/__mocks__/selectors.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/SystemCard/SystemCard.js
src/components/GeneralInfo/SystemCard/SystemCard.test.js
src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
src/components/GeneralInfo/selectors/selectors.js
src/components/GeneralInfo/selectors/selectors.test.js
src/store/__snapshots__/systemProfileStore.test.js.snap

This PR addresses [ESSNTL-601](https://issues.redhat.com/browse/ESSNTL-601).
It adds a "System purpose" field in-between "SAP" and "Number of CPUs", and its value is equal to `system_profile.system_purpose.usage`.

Add System Purpose field to system card

---

src/Utilities/TagsModal.js
src/Utilities/constants.js
src/api/api.js
src/api/tagsApi.test.js
src/components/InventoryTable/EntityTableToolbar.js
src/store/inventory-actions.js

This is a follow-up PR to fetch tags for stale_warning systems also. It looks like the UI needs to pass all staleness filters to get all existing tags. 
To test:
1. navigate to the Inventory app
2. Verify that the API req to /tags is made with parameters staleness =  'fresh', 'stale', 'stale_warning', 'unknown'.
3. Verify that the tags modal opens as expected
4. Verify that the pagination works as expected

fix(TagsApi): ESSNTL-3427 add fetch tags for all stale status

---

src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
src/components/filters/__snapshots__/useOperatingSystemFilter.test.js.snap
src/components/filters/useOperatingSystemFilter.js
src/components/filters/useOperatingSystemFilter.test.js
src/modules/OsFilterHelpers.js
src/store/entities.js

Implements https://issues.redhat.com/browse/ESSNTL-3341 and has to be merged only after https://github.com/RedHatInsights/insights-inventory-frontend/pull/1638.
This makes the systems table render OS filter with the single empty value "No versions available" if there is a network request error or the request is successful but doesn't have any values (empty array).

Render "No versions available" if there are no OS versions available

---

config/setupTests.js
src/Routes.js
src/components/GeneralInfo/LoadingCard/LoadingCard.js
src/components/InventoryDetail/InventoryDetail.js
src/components/InventoryTable/EntityTable.test.js
src/routes/InventoryDetail.js

There are 4 commits in the PR:
- For clickable elements that are used to open modals, don't append params and anchors to the URL
- Removal or routing workaround that was introduced before BZ1958379 was closed
- Modals in the general info page can now be routed directly 
- Test updates

ESSNTL-3456 - Hyperlink titles get into global filter tag and breaks everything

---

config/setupTests.js
src/components/GeneralInfo/LoadingCard/LoadingCard.js
src/components/InventoryDetail/InventoryDetail.js

There's an error when navigating to inventory detail from different application. The reason is that inv detail is looking at active system by parsing the URL. Each app defines the place where react-router-dom should look for inventoryId, however current implementation blindly checks for first string in URL. It results in broken UI where inventory is requesting URLs like `/api/invenotory/v1/hosts/inventory`.

Fix inventory detail by using useParams instead of useRouteMatch

---

src/components/InventoryTable/EntityTable.js
src/components/InventoryTable/hooks/useColumns.js
src/store/entities.js

**Steps to reproduce:**
1.) Open the "Settings" -> "Remote Host Configuration" page.
2.) Click the top right "View log" link
3.) Go to the "Systems" tab (Make sure there are systems in the list, otherwise the error is not triggered)
4.) Close the modal.
5.) Enter `window.__scalprum__.scalprumOptions.cacheTimeout = 1;` into the console to force a lower module cache timeout.
6.) After waiting reopen the "View log" modal
On Prod/Stage this should throw errors and not load the inventory. With this PR the errors should not occur and the Inventory should load normally.

fix(InventoryTable): ESSNTL-3505 - Only use columns already in the store

---

src/components/GeneralInfo/BiosCard/BiosCard.test.js
src/components/GeneralInfo/CollectionCard/CollectionCard.test.js
src/components/GeneralInfo/ConfigurationCard/ConfigurationCard.test.js
src/components/GeneralInfo/ConfigurationCard/__snapshots__/ConfigurationCard.test.js.snap
src/components/GeneralInfo/DataCollectorsCard/DataCollectorsCard.test.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.test.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/InfrastructureCard/InfrastructureCard.js
src/components/GeneralInfo/InfrastructureCard/InfrastructureCard.test.js
src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
src/components/GeneralInfo/LoadingCard/LoadingCard.js
src/components/GeneralInfo/LoadingCard/LoadingCard.test.js
src/components/GeneralInfo/LoadingCard/__snapshots__/LoadingCard.test.js.snap
src/components/GeneralInfo/OperatingSystemCard/OperatingSystemCard.test.js
src/components/GeneralInfo/SystemCard/SystemCard.test.js
src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.test.js
src/components/InventoryDetail/InventoryDetail.js
src/routes/InventoryDetail.js

When opening new tab from General information links the UI breaks because inventory ID is incorrectly calculated. This PR fixes it by consuming `inventoryId` from parent component (which should know about what is active by checking the router param). We should go around all apps and adapt to this new behavior, once that is done we can remove the wrapper component.

Fix clicking on gen info detail links

---

package-lock.json
package.json

Updates **@redhat-cloud-services/host-inventory-client** to 1.0.116 to have new system update method filtering in the API.

chore(deps): bump host-inventory-client to 1.0.116

---

.eslintrc.yml
.gitignore
.travis.yml
babel.config.js
config/cypress.webpack.config.js
coverage.sh
cypress.config.js
cypress/support/commands.js
cypress/support/component-index.html
cypress/support/component.js
package-lock.json
package.json
src/components/SpinnerFallback.cy.js

This installs the cypress and its dependencies, creates default configuration files, adds npm commands and creates an  example spec to verify that components are built correctly using cypress webpack config.
1. You should be able to run `npm run test:ct` and `npm run test:openct`. Both commands must show the only example component test with the spinner component.
2. Running both `npm run test` and `npm run test:ct` must generate `codecov-jest` and `codecov-cypress` directories accordingly. Running `npm run coverage` must generate the final coverage report and attempt to upload it to a server.

chore: Set up cypress and component testing

---

src/Utilities/constants.js
src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
src/components/filters/useStalenessFilter.test.js
src/routes/InventoryTable.js
src/store/entities.js
src/store/inventory-actions.js

Resolves: [ESSNTL-3914](https://issues.redhat.com/browse/ESSNTL-3914)
This removes default filtering completely while adding the 'Unknown' option into the status filter to be able to filter by all 4 options.
To test:
1. Visit the inventory app
2. observe that there is not any active filter by default
3. open the status filter, and observe that there is a new option 'Unknown'
4. play with the filtering: should persist refresh, should be added into URL, should filter as expected

Stale fitler

---

src/api/api.js

Updates the api to accept perPage and page params. There is currently a bug in [advisor](https://issues.redhat.com/browse/ADVISOR-2957) where perPage is never read, and always goes to the default 50 items per page. This means that when selected 100, only 50 can be seen. In this case 51 will appear, but the 51st item will take you to a broken page. It seems this api was updated elsewhere and this little segment was just forgotten.
To test :
- Run advisor via  npm run start:proxy -- --port=8004
- the run this inventory pr via LOCAL_API=advisor:8004~https npm run start:proxy
- Go to advisor /recommendations
- Select a recommendation to go to the rec details page (inventory table is here)
- Select 100 items per page 
Old result:
- 51 items appear, the last one breaks
Results expected with …

fix(ADVISOR-2957): updates api to accept perPage+page params

---

src/AppEntry.js
src/Utilities/constants.js
src/Utilities/sharedFunctions.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTable/InventoryTable.test.js
src/components/InventoryTable/InventoryTableInitialLoading.test.js
src/components/SystemDetails/GeneralInfo.js
src/components/SystemDetails/Patch.js
src/components/SystemDetails/Ros.js
src/components/SystemDetails/Vulnerability.js
src/store/index.js
src/store/reducers.js
src/store/registeryContext.js

This PR resolves the issue **Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization** on stage-beta after a hard refresh on inventory pages on consumer apps. The culprit was circular deps between store/index.js and all of the activeApp components in the reducer context.
I will get rid of activeApps in the reducer as a next step improvement.
To test:
1. Please run the app with other consumer apps (Patch, vuln...)
2. Verify that all apps work together 
3. Hard refresh does not break any app
4. Inventory detail page on Inventory app works for all tabs.
Circular dep before:
Circular dep after:

fix: get rid of circular deps to avoid early access registery context

---

.travis.yml
README.md
package-lock.json
package.json

This enables versioning of insights-inventory-frontend and automatic generation of CHANGELOG.md.
The required GH and NPM tokens are set up at https://app.travis-ci.com/github/RedHatInsights/insights-inventory-frontend/settings.

chore: Set up semantic-release support

---

README.md
config/dev.webpack.config.js
package-lock.json
package.json

Implements https://issues.redhat.com/browse/ESSNTL-4219.
This provides another local deployment option where webpack server starts together with the mocked API server. The API server is built on top of OpenAPI schema.
prism CLI docs: https://docs.stoplight.io/docs/prism/674b27b261c3c-overview
1. Check updated README.md and follow the steps.
2. While deployed locally, verify that HBI API endpoints are redirected to local prism server.

chore(ESSNTL-4219): Run with mocked API server

---

package-lock.json
package.json
src/Routes.js
src/components/InventoryGroups/NoGroupsEmptyState.js
src/components/InventoryGroups/__tests__/NoGroupsEmptyState.test.js
src/components/InventoryGroups/index.js
src/routes/InventoryGroups.js

Implements https://issues.redhat.com/browse/ESSNTL-3724.
This adds a new route /groups that leads to the groups table page. Now the page defaults to empty state in all cases and doesn't perform any network requests.
Navigate to /insights/inventory/groups; check the header and empty state are rendered. Buttons and links are not expected to work at the moment.

feat(ESSNTL-3724): Add /groups route & empty state

---

src/Routes.js

This makes Inventory hide /groups page component if the feature flag is set to false.
1. Deploy the PR locally using stage environment.
2. Go to https://insights-stage.unleash.devshift.net/projects/default/features/hbi.ui.inventory-groups.
3. Set the flag to true in default and then check that the /groups page is rendered.
4. Set the flag to false in default and then check that the /groups page is not rendered and return 404 page.

refactor(ESSNTL-3724): Connect /groups to feature flags

---

.github/dependabot.yml

Let's extend `dependabot` checking interval to a weekly manner. This will most probably not miss any updates. It might just aggregate some updates.

chore: extend dependabot checking interval

---

src/components/SystemDetails/Patch.js

Passes inventory id as a prop to Patch module. This prop is required after [this PR](https://github.com/RedHatInsights/patchman-ui/pull/956) to render system detail components.
To test please run both PR together and make sure no application breaks. Functionality should not change.

chore(RHIF-171): pass inventoryId to Patch module as a prop

---

src/__mocks__/mockedGroups.json
src/components/InventoryGroups/utils/api.js
src/store/action-types.js
src/store/actions.test.js
src/store/groups.js
src/store/index.js
src/store/inventory-actions.js
src/store/reducers.js
src/store/reducers.test.js

Implements https://issues.redhat.com/browse/ESSNTL-4194.
This adds reducer and related actions to enable fetching groups from /api/inventory/v1/groups.
Try to call `dispatch(fetchGroups())` in any of the components and check whether Redux devtools fires `GROUPS_PENDING` and `GROUPS_FULFILLED` or `GROUPS_REJECTED` redux actions.

chore(ESSNTL-4194): Implement Inventory groups reducer

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/InventoryTable.test.js
src/components/InventoryTable/InventoryTableInitialLoading.test.js
src/routes/InventoryTable.test.js

Hides the System update method filter with a feature flag.
1. Run the PR locally on the stage environment.
2. Go to https://insights-stage.unleash.devshift.net/projects/default/features/hbi.ui.system-update-method.
3. Set the flag to true in default and then observe that the filter is shown.
4. Set the flag to false in default and then observe that the filter is hidden.

chore(RHIF-169): hide system update method filter untill API is ready

---

config/cypress.webpack.config.js
config/setupTests.js
package-lock.json
package.json
src/components/InventoryGroups/Modals/CreateGroupModal.cy.js
src/components/InventoryGroups/Modals/CreateGroupModal.js
src/components/InventoryGroups/Modals/CreateGroupModal.test.js
src/components/InventoryGroups/Modals/Modal.js
src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
src/components/InventoryGroups/NoGroupsEmptyState.js
src/components/InventoryGroups/__tests__/NoGroupsEmptyState.test.js
src/components/InventoryGroups/helpers/validate.js
src/components/InventoryGroups/utils/api.js
src/components/InventoryGroups/utils/apiWithToast.js

Create group modal for inventory groups
To test the modal run "npx cypress open --component"
or you can add the CreateGroupModal to another component in the inventory. In this case, it will render but crash as soon as you make an API request for group name validation
OR you can open it in stage-beta
by opening the https://stage.foo.redhat.com:1337/beta/insights/inventory/groups and clicking on the "Create group" button

feat(inventory grops): group name modal 

---

src/components/SystemDetails/Advisor.js

Currently AdvisorTab doesnt load. This prop needs to be passed it, (its passed down in advisor).
Related PR : https://github.com/RedHatInsights/insights-advisor-frontend/commit/7feca8f0d576848ae3e49d156a9b703c35d93caa

fix(ESSNTL-4387): pass down inventoryId to Advisor

---

cypress/support/interceptors.js
src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js
src/components/InventoryGroups/Modals/CreateGroupModal.js
src/components/InventoryGroups/Modals/DeleteGroupModal.cy.js
src/components/InventoryGroups/Modals/DeleteGroupModal.js
src/components/InventoryGroups/Modals/RenameGroupModal.js
src/components/InventoryGroups/utils/api.js

Implements https://issues.redhat.com/browse/ESSNTL-4365.
- Connects modals to the appropriate action buttons in the groups table.
- Improves the delete group modal so that it can accept more group IDs and perform the deletion request with multiple IDs.
1.  Run `npm run mock-server` and `npm run start:mock:beta` in separate terminals.
2. Navigate to https://stage.foo.redhat.com:1337/beta/insights/inventory/groups.
3. Use toolbar or per-row actions kebab to use the features on selected groups.
4. Check the right network requests are made after performing any action. (visually there can be some bugs due to the mocked crazy API).
5. Check the components tests pass.

feat(ESSNTL-4365): Enable actions in the groups table

---

package.json
src/components/GroupsTable/GroupsTable.cy.js

This PR 
1. **rewrites some flaky tests** that assert network requests and their search parameters (e.g. filter, sorting, etc.). The problem is that cypress doesn't wait or flush all the requests between `it`s and thus some tests can assert on wrongly intercepted requests. It must be resolved now by `cy.wait`ing for all requests that we set up interceptors for.
1. Example: the inventory groups table makes the initial request for all data via GET `/groups`. If in the tests we change the pagination and then `cy.wait` for the new paginated request, then it can happen that the first requests hasn't been finished yet and `cy.wait` will catch the very first request instead of the request made after changing pagination (the one we need to check).
2.  **makes cypress run component tests in …

test: Stabilize cypress component tests

---

cypress/support/interceptors.js

This rewrites some interceptors to always have the third argument compliant with the interceptors' response object interface (e.g., always include statusCode, body): https://docs.cypress.io/api/commands/intercept#Response-object-properties. This should help avoid "flakiness" for some tests and make the test code utils consistent.
The component tests must pass.

test: Bring intercept responses to one format

---

cypress/fixtures/groups/Ba8B79ab5adC8E41e255D5f8aDb8f1F3.json
src/components/InventoryGroups/utils/api.js
src/store/actions.test.js

This serves as a temporary solution for the missing GET endpoints implementation on the API level. This will allow QEs to open the views and find required components selectors.

chore: Mock GET groups related requests

---

src/Utilities/constants.js
src/components/InventoryTable/EntityTableToolbar.js
src/components/filters/useLastSeenFilter.js
src/constants.js
src/routes/InventoryTable.js

To test new updates check for the following:
When selecting last seen filter, if you refresh, filter persist
- Make sure you can copy/past the link with the filter present (this is true for all except custom, custom should populate the range picker)
- Make sure Start Date cant be larger than End Date
- Make sure End date cant be smaller than start Date
- End date and start date both cannot go past Todays date
-Should be able to delete both values manually
Filter should not break ever. I believe this PR should catch all edge cases

ESSNTL(4056): Adds checks against edge cases for last seen filter

---

src/routes/InventoryTable.js

This adds a fallback value for lastSeenFilter object which appears to be undefined or null in some CI tests.

fix: Fix the CI error related to lastSeen filter

---

src/routes/InventoryDetail.js
src/store/reducers.js

ROS team brought to our attention that their tab is always hidden on inventory detail. This happend because of recent inventory refactoring and we forgot to move certain part of the code. This PR re-enables it and also removes unused part of redux code which was used in the past to calculate the visibility.
https://github.com/RedHatInsights/insights-inventory-frontend/pull/1435

fix(RHCLOUD-24793): Show ROS tab is azure or aws cloud provider

---

cypress/fixtures/hosts.json
cypress/support/interceptors.js
src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js
src/components/GroupSystems/index.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/components/InventoryGroupDetail/InventoryGroupDetail.js
src/components/InventoryGroupDetail/NoSystemsEmptyState.js
src/components/InventoryGroupDetail/__tests__/InventoryGroupDetail.test.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
src/components/InventoryGroups/Modals/ConfirmSystemsAddModal.js
src/components/InventoryGroups/Modals/CreateGroupModal.js
src/components/InventoryGroups/Modals/Modal.js
src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
src/components/InventoryGroups/Modals/RenameGroupModal.js
src/components/InventoryGroups/utils/api.js
src/store/entities.js

Implements https://issues.redhat.com/browse/ESSNTL-3728.
Mocked at https://www.sketch.com/s/c19f555b-7887-4423-b55d-575c8dd1dfb7/a/8yK3wl3.
This gives functionality to "Add systems" button in the empty state and also on the top of group systems table (/groups/%id view). The user is given the list of systems and chooses which to add to the current group. If one of the selected systems is already in a group, then the user is additionally prompted for confirmation.
Be able to reproduce user flows from the mocks. Check the API requests are called and contain the required data about systems and groups.
(the columns order has changed since https://github.com/RedHatInsights/insights-inventory-frontend/pull/1798/commits/d147b0641931510a3c52d29c196a9255a1db5ee7)

feat(ESSNTL-3728): Enable multiple hosts addition to group

---

src/components/GroupSystems/GroupSystems.cy.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js

`prepareColumns` could send array containing `undefined` values (e.g., for the Group column because it depends on the feature flag setting). This PR puts more safety in managing this column: filters out `undefined` values and also makes sure the test has the feature flag set to true.
https://github.com/RedHatInsights/insights-inventory-frontend/blob/d3181ba5b5923847c7c02b5e5af9176fe54ed406/src/components/GroupSystems/GroupSystems.cy.js#L314 should pass.

test: Fix failing AddSystemsToGroupModal test

---

src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js

Fixes https://issues.redhat.com/browse/ESSNTL-3727.
Hides the Group filter on the group systems view (/groups/%id).

fix(ESSNTL-3727): Hide Group filter

---

src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js

Fixes https://issues.redhat.com/browse/ESSNTL-3728.
This goes over minor bugs in the systems table that are present in the hosts addition modal.

fix(ESSNTL-3728): Fix links, show missing tags filter

---

src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js

Fixes: https://issues.redhat.com/browse/ESSNTL-4628.
Aligning order of the columns in the inventory table and systems table for Group + add systems Modal for Group
Sketch https://www.sketch.com/s/ee66c23d-3d18-4940-afdf-e8a3c983d22d/a/5n2kMwd
Group systems table
Modal

fix(inventory groups): changed the column order to allign with the app

---

src/components/InventoryTable/InventoryTable.js

Compliance adds filters via the `activeFiltersConfig` prop and not the `customFilters` prop and does not use the redux store to keep active filters and does therefore not trigger a refresh properly and only the first filter change in compliance would trigger a refresh, or if a filter is used coming from the inventory, like tags.
How to test:
* Run inventory locally, possibly also with compliance
* Open the Compliance -> Systems page
* Filter by name, or any other "compliance filter"
* Add to the filter and the table should refresh again
The last step would fail without this change.

fix(InventroyTable): Add activeFiltersConfig to prop cache to trigger refresh

---

src/components/InventoryTable/InventoryTable.js

This should fix instances where filter chips would not properly appear, for example on Patch -> Systems.

fix(InventoryTable): Pass on activeFiltersConfig properly

---

src/Utilities/InsightsDisconnected.js

This PR is just fixing a small typo.
`s/Registration Assitant/Registration Assistant/`

RHINENG-383: Fix typo in the tooltip when insights client is not reporting

---

src/Utilities/constants.js

In an effort the remove this lastseen custom blocker of inventory release, temporarily removing the custom value from the drop down and remove ability to select custom dates.

chore(customDate): remove custome date

---

src/components/InventoryTable/InventoryTable.js

This fixes a random issue on the Inventory table. When you enter a string into the display name filter and remove the filter one char at a time in the input element and then sort by any column, the display name filter gets reset. 
**To test** the issue happens randomly, but this way seems more frequent, so please play with the filter and sorting more:
1. Go to the inventory app and table
2. Search for a string
3. delete the filter one by one in the input
4. sort the table by any column
5.  observe that the filter is still active

fix(ESSNTL-4714): fix display name unwanted reset on sort

---

src/components/InventoryTable/EntityTableToolbar.test.js
src/components/filters/useGroupFilter.js
src/components/filters/useGroupFilter.test.js
src/routes/InventoryTable.js

Fixes https://issues.redhat.com/browse/ESSNTL-4791.
This makes sure Inventory doesn't make any network calls to the groups endpoints if the feature flag is disabled.
1. Deploy locally with `ENVIRONMENT=prod npm run start:proxy`
2. (optional) Make sure https://insights.unleash.devshift.net/projects/default/features/hbi.ui.inventory-groups is disabled
3. Navigate to https://prod.foo.redhat.com:1337/insights/inventory, log in
4. Make sure the table is rendered, there is no filter "Group" available, the column "Group" is not rendered, and there are no requests to /api/inventory/v1/groups*-like endpoints in the network tab.

fix(ESSNTL-4791): Hide all /groups requests under feature flag

---

.travis.yml

This changes the deployment step to use travis:build instead of regular build. This helps to avoid possible problems with serving correct assets according to environments.

chore: use travis:build for travis deployment

---

src/components/InventoryGroups/Modals/AddHostToGroupModal.js
src/components/InventoryGroups/utils/api.js
src/routes/InventoryTable.js

Fixes https://issues.redhat.com/browse/ESSNTL-3730.
This makes the "add host to group" modal pass correct host ID and thus send correct API request. Previously, the group's ID in the network request was always equal to `undefined`.
1. Run `npm run start:proxy:beta`
2. Authenticate with `insights-qa`, navigate to https://stage.foo.redhat.com:1337/preview/insights/inventory.
3. Select any system and add it to a group.
4. After submit, in the network tab, make sure the POST /groups/... request contains correct ids of both group and added system.

fix(ESSNTL-3730): Fix Add host to group API call

---

src/routes/InventoryTable.test.js
src/store/actions.js
src/store/inventory-actions.js

After https://github.com/RedHatInsights/insights-inventory-frontend/pull/1847/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R19 upgrade, it turned out some `javascript-clients` functions changed their naming. This updates the places where incorrect function were called.
Deploy the PR, navigate to Inventory and try to change display name, ansible name or delete host. The operations must be completed successfully and without errors.

fix(ESSNTL-4486): Update API functions names

---

src/components/InventoryTable/InventoryTable.js

Ticket: [ESSNTL-4812](https://issues.redhat.com/browse/ESSNTL-4812)
Global filter now works after refresh
How to test:
1. Open Stage Beta and select a global filter
2. Notice the system count
3. Refresh and notice the system count is different
4. Now run my PR, select the same global filter and refresh
5. Notice the system count stays the same

fix(ESSNTL-4812): Fix Global filter on refresh

---

src/components/GroupsTable/GroupsTable.js

How to test the fix: 
1. Open groups table https://stage.foo.redhat.com:1337/preview/insights/inventory/groups
2. Select several groups
3. Click on the kebab button and try to delete the group. 
4. The modal should have the name of the group from the same row that you clicked to open delete modal.
5. Try to delete these selected groups - only group from the clicked row should be deleted.
6. Try to do the same (repeat step 1 and 2) then click on the actions in the Toolbar of the table and try to delete several groups at once.

fix(essntl-3736): fix for group deletion

---

src/components/GeneralInfo/OperatingSystemCard/OperatingSystemCard.js
src/components/GeneralInfo/selectors/selectors.js

Resolves: https://issues.redhat.com/browse/ESSNTL-3578
To test:
1. Open the inventory app
2. Select any system that is not disconnected from insights
3. Observe that a new 'Update method' field has appeared in **Operating system** card
TODO: will cover with cypress test after https://github.com/RedHatInsights/insights-inventory-frontend/pull/1865 gets merged.

feat(ESSNTL-3578): show update method field in details page

---

src/components/InventoryGroups/Modals/AddHostToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddHostToGroupModal.js
src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
src/components/filters/useGroupFilter.js

This is the same PR as https://github.com/RedHatInsights/insights-inventory-frontend/pull/1867 but with a FIX that prevents infinite loads. 
How to test
Try to find a host in the inventory table that is not in a group. Click "Add to group" and try to type some input in the groups search. The network requests to GET /groups must contain a name parameter with the input you have typed.
Make sure that if you type the group name in the search field - the search won't go "infinite spinner mode" and will either fail to find(if you are typing the name of the not existing group) or find a group you want.

Add host to group

---

src/components/InventoryTable/InventoryList.js
src/routes/InventoryTable.cy.js
src/routes/InventoryTable.js

Implements https://issues.redhat.com/browse/ESSNTL-3730, https://issues.redhat.com/browse/ESSNTL-3733.
This makes the inventory table reload data when the host is added to or removed from a group via action modals. This also fixed the wrong `ref` property propagation.
1. Go to the inventory table
2. Try to add (the network call will fail - this is expected currently) to or remove hosts from groups (the "test" group has some hosts in `insights-qa` profile)
3. Check that after submit the rows are reloaded with the **same** filters.

fix: Reload table when changing the host group

---

cypress/fixtures/groups.json
cypress/fixtures/hosts.json
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
src/components/InventoryGroups/Modals/RemoveSelectedHostsFromGroupModal.js
src/components/InventoryGroups/utils/api.js
src/routes/InventoryTable.cy.js
src/routes/InventoryTable.js

Implements https://issues.redhat.com/browse/ESSNTL-3731, https://issues.redhat.com/browse/ESSNTL-4197.
This makes it possible to select more hosts and remove or add the to groups.
1. Navigate to the inventory table
2. Select more hosts which are not in any group
3. Try to add them to existing group via the Add to group action. In the end you should see the failing network request with 405 status code - it is expected for now.
4. Try to remove hosts from the same group via the Remove from group action. The endpoint is implemented and the operation must be successful. Check the hosts are truly removed from the group.

feat: Enable bulk hosts addition/removal to/from groups

---

src/components/InventoryGroups/Modals/AddHostToGroupModal.js
src/components/InventoryGroups/utils/api.js
src/routes/InventoryTable.cy.js

(no jira)
This makes the AddHostToGroupModal use the same endpoints as in the groups systems table. The previous has implementation problems and is still not available to use. The working once receives the list of hosts to add in the body instead of listing them in URL.
1. Navigate to /inventory
2. Select any host which is not in a group
3. Add the host to any group and make sure the operation is successful

fix: Use the same endpoint to add hosts to group

---

src/store/systemProfileStore.js
src/store/systemProfileStore.test.js

The `enabled` field in repository configurations defaults to 1, so consider repositories where this option is missing as enabled.

fix(systemProfileStore): Repositories are enabled by default

---

src/routes/InventoryTable.js

On the systems page (/inventory), the bulk addition to or removal from a group must be hidden if the feature flag is set to false.

fix: Hide bulk add to/remove from group under FF

---

src/Utilities/constants.js
src/components/filters/helpers.js
src/components/filters/useLastSeenFilter.js

This PR enables custom Dates for last seen filter and addresses additional edgecases discussed here : https://issues.redhat.com/browse/ESSNTL-4746 
To test, select the last seen filter custom option,
type in unique characters like {{' , '2023-04-21' in the end date field and make sure it doesnt break anything.
For the second edge case, input two identical FUTURE dates in first the end date and then in the start date inputs. Then erase the end date input. Verify that nothing breaks.

fix(ESSNTL-4745):Enable custom dates for lastSeen filter

---

src/components/InventoryGroups/InventoryGroups.js

jira: https://issues.redhat.com/browse/RHCLOUD-26362
The `useEffect` hook can't use async callback function. Any async side effects have to be lifted out of the hook.

Lift async use effect callback.

---

src/Utilities/Wrapper.js

The permissions are too strict, this high up.
Read permissions should be enough to view an inventory component.
1) Create an user with only the "Compliance viewer" role
2) Visit the Compliance -> Systems page
3) With this the page should be accessible

fix(RederWrapper): ESSNTL-4954 - Remove check for all permissions

---

cypress/support/interceptors.js
package-lock.json
package.json
src/components/InventoryGroupDetail/GroupDetailHeader.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/components/InventoryGroups/Modals/DeleteGroupModal.js

Fixes https://issues.redhat.com/browse/RHINENG-747.
Users should stay on the same page and the data they see must be not reloaded after closing group deletion modal.
1. Find an Inventory group with at least one host and go to its details page.
2. Try to delete the group. You should see the modal saying you are unable to do that.
3. Click on the Close button and make sure the page is not reloaded/navigated to another view.

fix(RHIENG-747): Fix the group delete modal behavior

---

src/components/filters/helpers.js
src/components/filters/useLastSeenFilter.js

The backend returns a 503 in specific scenarios, this PR adds additional edge cases to lastSeen filter while the backend figures out the issue. This also allows the check on both ends. 
To test, 
Try entering random strings in the custom date inputs, 
Try entering incomplete dates, like 201 or 192,
Enter years well past our time like 1900s

fix(ESSNTL-4746): LastSeen filter backend edge case

---

src/Utilities/constants.js
src/Utilities/sharedFunctions.js
src/Utilities/sharedFunctions.test.js
src/components/InventoryDetail/ApplicationDetails.js
src/components/InventoryDetail/DetailHeader.js
src/components/InventoryDetail/FactsInfo.js
src/store/entities.js

Fixes https://issues.redhat.com/browse/RHINENG-736.
This manipulates a couple of things:
- Makes usage of support function to check staleness more generic
- Introduces checking of RHSM systems to/not display Patch and Vulnerability modules.
As this touches multiple places, increased attention would be appreciated.

fix(RHINENG-736): Vulnerability and Patch tab in Inventory don't show data for RHSM stystems

---

cypress/support/commands.js
src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js
src/components/InventoryGroups/InventoryGroups.cy.js
src/components/InventoryGroups/InventoryGroups.js
src/routes/InventoryGroups.js
src/routes/InventoryGroups.test.js

Implements https://issues.redhat.com/browse/ESSNTL-4935.
The /groups view must disable actions if users don't have `inventory:groups:write` permission.

feat(ESSNTL-4935): Should disable actions at /groups

---

src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js

Implements https://issues.redhat.com/browse/ESSNTL-4934.
This makes the groups table render 'N/A' if users do not have hosts read permissions.
1. Log into account that doesn't have the `inventory:hosts:read` permission
2. Open the groups page (/inventory/groups), and make sure all "Total systems" values are N/A.

feat(ESSNTL-4934): Hide host number if users are not allowed

---

src/components/GeneralInfo/GeneralInformation/GeneralInformation.js

Item sorted ascendingly are fixed, sorted from A-Z. This might impact numbers, as those would be also ASC starting from 0.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
ESSNTL-3473
RHINENG-737

fix(popover): sorting a-z

---

src/components/InventoryGroups/InventoryGroups.cy.js
src/components/InventoryGroups/NoGroupsEmptyState.js

Implements https://issues.redhat.com/browse/ESSNTL-4935.
This is a follow-up on https://github.com/RedHatInsights/insights-inventory-frontend/pull/1914: this PR should disable Create group button when there are no groups and users do not have the write permission.
Make sure you don't have any groups and the account is missing inventory:groups:write. Check that the Create group at /groups page is disabled.

feat(ESSNTL-4935): Check permissions in no groups state

---

src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/components/InventoryGroupDetail/NoSystemsEmptyState.js

Should be merged after https://github.com/RedHatInsights/insights-inventory-frontend/pull/1920.
Implements https://issues.redhat.com/browse/ESSNTL-5041.
This makes additional check for `inventory:hosts:read`: if the permissions exists, then the Add systems button is enabled.
Have an account with both read and write groups permissions, but hosts read missing. Check that the Add systems button is disabled on the /groups/%id page.

feat(ESSNTL-5041): Add hosts only if has hosts read permissions

---

src/components/GroupsTable/GroupsTable.js
src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
src/components/InventoryGroupDetail/GroupDetailInfo.js
src/components/InventoryGroups/NoGroupsEmptyState.js
src/constants.js
src/routes/InventoryGroups.js

Implements https://issues.redhat.com/browse/ESSNTL-4938.
This makes sure we check for the inventory groups administrator permissions: if exist for user, then enable the "Manage access" button on /groups/%id.
Log in to user without inventory:groups:read or inventory:groups:write permissions. Go to any group and select the tab "Group info". The button Manage access must be disabled.

feat(ESSNTL-4938): Disable Manage access if not allowed

---

src/components/InventoryGroupDetail/EmptyStateNoAccess.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/components/InventoryGroupDetail/InventoryGroupDetail.js
src/components/InventoryGroupDetail/__tests__/InventoryGroupDetail.test.js
src/routes/InventoryGroups.js

Implements https://issues.redhat.com/browse/ESSNTL-4937.
Adds additional check for inventory:hosts:read in order to decide whether to show the group systems or not. On page /groups/%id.

Check for hosts:read before showing group hosts

---

cypress/support/commands.js
src/App.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
src/modules/AsyncInventory.js

Fixes https://issues.redhat.com/browse/ESSNTL-5052.
We forgot to add `checkResourceDefinitions` flag to RBACProvider, and, thus, all RBAC checks were not taking RD into account. This, for example, impacted the linked Jira bug.
Make sure you have `inventory:hosts:*` and `inventory:hosts:read` permissions. Also, you must not have `inventory:hosts:write` permissions. Go to /inventory and find any system which is not in a group. Open the addition to group modal and make sure "Create a new group" is disabled.

fix(ESSNTL-5052): Opt in resource definition check everywhere

---

src/components/SystemDetails/GeneralInfo.js

After Edge image details federated module was merged some time ago, this new section was be showed to all images (DNS/OSTree). This PR will add an origin validation to just show when host is Edge. 
Ticket: [THEEDGE-3466](https://issues.redhat.com/browse/THEEDGE-3466)

fix: Show image details just show when edge hosted image

---

package-lock.json
package.json
src/components/GroupSystems/GroupSystems.cy.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/constants.js
src/routes/InventoryGroups.js
src/routes/InventoryGroups.test.js

This fixes:
- Always show the groups table. It is safe since the back end must pre-filter results based on permissions.
- Fixes typo in RD key for groups
- Updates RBAC utils package so that the group details page doesn't crash.

fix: Address some of the RBAC and Inventory groups issues

---

src/Routes.js
src/Utilities/constants.js
src/constants.js
src/routes/InventoryDetail.js
src/routes/InventoryTable.cy.js
src/routes/InventoryTable.js
src/routes/InventoryTable.test.js

Implements https://issues.redhat.com/browse/ESSNTL-5043.
This changes the behavior of InventoryTable actions: now all the actions (delete host, add to group, etc.), both bulk and per-row, are **always** shown to users. However if a user doesn't have enough write permissions (inventory:groups:write or inventory:hosts:write), the actions are disabled with a information tooltip rendered on hover.
- This also disables RBAC check for the /inventory route: asking for ['inventory:hosts:read'] is strict because if users have this permission but limited with a resource definition, then they will still have no access to the page which is not correct.
1. Have an account for which you can manipulate permissions,
2. Go to /inventory,
3. Remove your `inventory:hosts:write` permissions and make sure you …

fix(ESSNTL-5043): RBAC and InventoryTable actions

---

src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js
src/components/InventoryGroupDetail/InventoryGroupDetail.js
src/constants.js

Fixes https://issues.redhat.com/browse/ESSNTL-4937.
This corrects the behavior of Total systems columns at /groups: we no longer want to calculate RBAC for each row (each group) and this is why the groups table now just renders the column value which comes from API.
With at least inventory:groups:read permission with RD enabled for your account, make sure the Total systems always renders the value which comes from the response from backend ("hosts_count" key).

fix(ESSNTL-4937): Don't check RBAC for Total systems column

---

src/Utilities/AccessDenied.js
src/components/InventoryGroupDetail/EmptyStateNoAccess.js
src/components/InventoryGroups/InventoryGroups.js
src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap

(no jira)
This makes the /groups page render the access denied message instead of "Something went wrong" when user doesn't have enough permission to see the groups table (lacks "inventory:groups:read").
Remove any "inventory:groups:read" permissions and try to open /groups. You have to see the "Inventory group access permissions needed" message.

feat: Improve 403 handling at /groups

---

.husky/pre-commit
.travis.yml
README.md
commitlint.config.js
package-lock.json
package.json

This:
- makes husky run JS and CSS linters as a pre-commit hook,
- adds configuration for commitlint and makes Travis check new commits for commit naming/description conventions,
- adds `verify:local` npm script that have test commands adjusted to the local setup (running jest **with** cache for faster tests, and also not collecting coverage afterwards).

chore: Add pre-commit lint hook, run commitlint

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/filters/useGroupFilter.js

Fixes https://issues.redhat.com/browse/ESSNTL-5064.
This fixes the groups filter in Inventory table: before, we were calling a wrong action, instead, we have to use the one that updates values under `entities`.
1. Go to /inventory
2. Try to apply the groups filter by more values, wait for refresh, and try again,
3. The table should show correct data and also update URL parameters accordingly.

fix(ESSNTL-5064): Fix groups filter by more values

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/EntityTableToolbar.scss

No jira.
At /inventory, this limits the height of the available groups list to 350px.
Go to /inventory. Open the groups filter, and make sure the height is no longer than 350px, and the scrollbar is rendered (if the list is long).

Limit the height of groups filter list

---

src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js

Fixes https://issues.redhat.com/browse/ESSNTL-5092.
Make sure you are able to sort by the Total systems column at /groups.

fix(ESSNTL-5092): Fix sorting by Total systems (/groups)

---

cypress/support/interceptors.js
src/components/GeneralInfo/BiosCard/__snapshots__/BiosCard.test.js.snap
src/components/GeneralInfo/CollectionCard/__snapshots__/CollectionCard.test.js.snap
src/components/GeneralInfo/ConfigurationCard/__snapshots__/ConfigurationCard.test.js.snap
src/components/GeneralInfo/DataCollectorsCard/__snapshots__/DataCollectorsCard.test.js.snap
src/components/GeneralInfo/EditButton/EditButton.js
src/components/GeneralInfo/EditButton/EditButtonWithAccess.test.js
src/components/GeneralInfo/EditButton/EditButtonWithNoAccess.test.js
src/components/GeneralInfo/EditButton/EditButtonWithNoAccessProd.test.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
src/components/GeneralInfo/LoadingCard/LoadingCard.js
src/components/GeneralInfo/LoadingCard/__snapshots__/LoadingCard.test.js.snap
src/components/GeneralInfo/OperatingSystemCard/__snapshots__/OperatingSystemCard.test.js.snap
src/components/GeneralInfo/SystemCard/SystemCard.test.js
src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
src/components/GeneralInfo/SystemStatusCard/__snapshots__/SystemStatusCard.test.js.snap
src/components/GeneralInfo/TextInputModal/TextInputModal.js
src/components/GeneralInfo/TextInputModal/__snapshots__/TextInputModal.test.js.snap
src/components/InventoryDetail/TopBar.js
src/constants.js
src/routes/InventoryDetail.cy.js
src/routes/InventoryDetail.js

Implements https://issues.redhat.com/browse/ESSNTL-5110.
This PR:
- Makes sure we always show **Delete**, **Edit display name** and **Edit Ansible hostname** buttons,
- Introduces more advanced check for the group level access: if user is eligible, the button is enabled, otherwise it is disabled with a helping tooltip,
- When user clicks on edit display name or ansible hostname buttons, the modal now has the Submit and Cancel buttons in the right order (more correct according to PF docs), and also the Submit button is disabled if the input value hasn't been changed.
For the RBAC change: 
1. make sure you have an account you adjust RBAC permissions/roles
2. verify, that you are able to press Delete and edit buttons while having just `inventory:hosts:write` permission (with the Inventory …

fix(ESSNTL-5110): Improve RBAC checks for delete and edit button on the System details view

---

src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js

This PR addresses [ESSNTL-4530](https://issues.redhat.com/browse/ESSNTL-4530).
It removes the rename option from the bulk action dropdown and adjust tests.

fix(ESSNTL-4530): remove rename from bulk actions

---

src/Utilities/Wrapper.js
src/components/InventoryTable/InventoryTable.js

https://issues.redhat.com/browse/ESSNTL-5176
BUG: 
the inventory table were crashing without :hosts:read permission.
It was caused by the fact that if rbacEnabled was false we were passing "true" to the inventory table. This "true" were causing api fetches, but because there were no permission for hosts -> table throws an error and crashes. 
I moved RBAC hasAccess check higher up the component tree to the Wrapper.js to prevent that and removed the condition.
Tested it with 3 different permissions:
No hosts:read permission
User have hosts:read permission

fix(ESSNTL-5176): inventory table access with no read permission

---

src/Utilities/constants.js
src/components/InventoryTable/ActionWithRBAC.js
src/routes/InventoryTable.cy.js
src/routes/InventoryTable.js
src/routes/InventoryTable.test.js

Implements https://issues.redhat.com/browse/ESSNTL-5206. The PR should be rebased, not squashed.
This makes the Inventory table Edit/Delete actions compliant with RBAC implementation requirements and Inventory groups:
<b style="font-weight:normal;" id="docs-internal-guid-398828c7-7fff-d2b3-b931-b4c0f06c8705"><div dir="ltr" style="margin-left:0pt;" align="left">
Edit | Enable if user has hosts:write for system selected (group-level RD check); disable otherwise
-- | --
Delete system | Enable if I have hosts:write for ALL systems selected (group-level RD check); disable otherwise
</div></b>
1. Leave only `inventory:hosts:read` permission for your user,
2. In the user access settings, for your username, set `inventory:hosts:write` to a specific group (the RBAC UI should allow that). So that …

Inventory table: check RBAC on the group level when enabling actions

---

src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
src/components/InventoryGroupDetail/GroupDetailInfo.js
src/components/InventoryTable/ActionWithRBAC.js
src/constants.js

Fixes https://issues.redhat.com/browse/ESSNTL-5209.
Enable the button and the link only when user has User Access Administrator role.
1. Find/create a group and navigate to its details page,
2. Add User access administrator role to your user and refresh the page. Make sure, at the Group info tab, you can see the Manage access button enabled.,
3. Remove the role and refresh the page. The button must be disabled.

fix(ESSNTL-5209): Manage access button and RBAC

---

cypress/support/commands.js
src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/components/InventoryGroupDetail/NoSystemsEmptyState.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js

Fixes https://issues.redhat.com/browse/ESSNTL-5172.
Make sure users can open the Add systems modal for any group they have a write permission (and not check for any other permission). Also changes the warning text inside the modal.
1. Add `inventory:groups:write` and `inventory:groups:read` permission with group-level access to any of the groups available to your user, and also `inventory:hosts` - same write and read - limited to this group,
2. Navigate to the group you set up permissions for,
3. Make sure you can add new systems (either from the empty state when there are 0 systems in a group, or from the table action otherwise).

fix(ESSNTL-5172): Alter permissions for add systems button

---

src/components/InventoryGroups/SmallComponents/Popover.js
src/routes/InventoryGroups.js

Implements https://issues.redhat.com/browse/RHIF-259.
Add a popover to Inventory groups title (/groups page).

fix: Add Inventory groups popover

---

src/components/GroupSystems/GroupSystems.cy.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
src/components/filters/__snapshots__/useGroupFilter.test.js.snap
src/components/filters/useGroupFilter.js
src/components/filters/useGroupFilter.test.js

Fixes https://issues.redhat.com/browse/ESSNTL-4924.
This should fix the groups filter: now the filter must fetch all available groups. Before, it was fetching only first 50 items.
Go to /inventory: the filter should display all of the available groups. Better to test with account having more groups.
Also, it is necessary to check some of the applications importing InventoryTable: if the filter still works well there with this update.

fix(ESSNTL-4924): Fetch all groups when building groups filter

---

src/components/InventoryGroupDetail/index.js
src/routes/InventoryGroups.js

Fixes https://issues.redhat.com/browse/ESSNTL-4667.
Keep the global filter always disabled at /groups and /groups/%id.

fix(ESSNTL-4667): Disable global filter at groups views

---

src/components/InventoryGroupDetail/GroupDetailInfo.js

No jira.
While fetching permissions the "Manage access" button (on /inventory/groups/%id) must be in a loading state.

fix: Add loading styling for manage access button

---

src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
src/routes/InventoryDetail.js

[ESSNTL-5048](https://issues.redhat.com/browse/ESSNTL-5048)
Fixed tab selection in Inventory detail, all search params are reset on tab change, so no filters are passed between tabs. Moved tab state completely to the searchParams
Removed some unused `useLocation`
1. Go to Inventory and select a system
2. Make sure `appName` is set in the url
3. Select Vulnerability tab and refresh
4. Go through different tabs and there should be no crashes
[Related Vulnerability PR](https://github.com/RedHatInsights/vulnerability-ui/pull/1951)

fix(ESSNTL-5048): Tab selection

---

src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
src/components/InventoryGroups/Modals/ModalSchemas/schemes.js

Fixes https://issues.redhat.com/browse/RHINENG-1420.
The add hosts to group modal was behaving weirdly when searching for groups: creating duplicates of the same results with each input change from user. This bug is caused by improper handling of objects as values for data-driven-form options: https://github.com/data-driven-forms/react-forms/issues/1401. This creates a workaround to fix this issue.
Go to /inventory and try to add any host to a new group. In the modal, make sure that the search for group works correctly and provides correct results.

fix(RHINENG-1420): Fix options duplicates in group search

---

src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.scss
src/components/InventoryGroups/Modals/Modal.js
src/components/InventoryGroups/SmallComponents/CreateGroupButton.js
src/components/InventoryTable/InventoryTable.cy.js

Fixes https://issues.redhat.com/browse/ESSNTL-5252.
This PR:
- makes the "Add selected hosts to group" modal hide the create group button when the user doesn't have general groups write permission.
- corrects the style for the modal so that the list of available groups is visible and can be easily scrolled.
Remove general `inventory:groups:write` from your account. Navigate to /inventory and try to add any host to a group. In the modal, you shouldn't see the "Create a new group" button.

fix(ESSNTL-5252): Hide Create a new group button if not permitted

---

src/api/api.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryTable/InventoryTable.cy.js
src/components/InventoryTable/InventoryTable.js
src/store/entities.js
src/store/inventory-actions.js
src/store/reducers.js

Fixes https://issues.redhat.com/browse/RHINENG-767.
This improves the behavior of the "Add systems" modal and fixes a couple of bugs:
- the modal now doesn't show all the unfiltered values if users click on Cancel or X before the entities are loaded in the modal,
- the modal now resets filters on close so that the settings are not wrongly propagated to the group systems table.
1) Navigate to any group details page where your group has at least one host
2) Click "Add systems", and while it is loading, quickly close the modal with X or Cancel. You should see the group hosts only again
3) Again click "Add systems" and try to apply any filters
4) Close the modal with Cancel or X. You shouldn't see the filters from modal applied to the group systems table (what was one of the bugs). …

fix(RHINENG-767): Fix add systems modal

---

src/components/GroupSystems/GroupSystems.cy.js
src/components/InventoryTable/EntityTable.js
src/components/InventoryTable/InventoryTable.cy.js
src/store/entities.js

- Fix columns missing names during loading in mobile view.
- Show checkboxes in the table skeleton if the loaded table contains them
- Show table headers when the table is loading
- Show current sort indicator when the table is loading
I checked other apps using Inventory table and I could only find one small regression -- Advisor shows double sorting indicator for some columns, I will fix this with PR in Advisor.

Update table skeleton

---

src/ApplicationTab.js
src/constants.js
src/routes/InventoryDetail.js

Fixes https://issues.redhat.com/browse/ESSNTL-5253.
Before rendering the application content in tabs on System details view, Inventory should check whether the user have enough viewer permissions for the selected app.
Remove any Viewer roles from other applications but Inventory. Go to any system details page and check the tabs: they should show that you the no access message. Try to add a Viewer role to any application, and check again the tab: you should see the application tab content rendered (e.g., Advisor recommendations for your system).

fix(ESSNTL-5253): Check tab permissions

---

config/overrideChrome.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
src/components/InventoryGroups/utils/api.js
src/constants.js

Fixes https://issues.redhat.com/browse/ESSNTL-5252.
While adding systems to existing group, provide to user only the groups that they have inventory:hosts:write permission. This help avoid errors when users accidentally add a host to the group they don't have access.
Also changing debounce timeout from 500 to 250 ms to make the UX a bit faster.
Limit your groups write permission to only specific groups. Navigate to /inventory and make sure, while adding a host to group, that you see only the groups you have write access to. Try to apply general write permissions and check that you see all of the groups available for your account.

fix(ESSNTL-5252): In Add system modal, load writable groups

---

src/routes/InventoryDetail.js

(no jira)
This improves how the system details page change the browser history on navigating between tabs. Users used to stay on the same host details page if they clicked on different tabs like Advisor or Patch and then tried to click on browser's Back/Forward button. This is not really comfortable, and pressing Back should navigate to the previous page instead. To do this, the current browser's history entry should be replaced instead of adding a new one.
Go to /inventory and navigate to any host details page. Click on tabs, then click Back in your browser and make sure you are navigated back to /inventory table (users used to stay on host details page which is not expected behaviour).

fix: Do not add history entry on host details page

---

src/ApplicationTab.js
src/routes/InventoryDetail.js

Fixes https://issues.redhat.com/browse/ESSNTL-5253.
This is another patch for ESSNTL-5253 that makes sure that all of the params are passed to the tabs components and the tabs are loaded correctly.
Go to any system details page, access the Patch or other tabs: there shouldn't be any errors and the tabs are not breaking. You can compare with stage-preview where the bug is still reproducible.

fix(ESSNTL-5253): Fix the broken inventory details tabs

---

package-lock.json
package.json
src/App.js
src/ApplicationTab.js
src/constants.js

Fixes https://issues.redhat.com/browse/ESSNTL-5253. Should be merged after https://github.com/RedHatInsights/frontend-components/pull/1900 is released.
With this PR, Inventory fetches permissions for all applications, not only from the inventory scope. This way, we can read all the required permissions before rendering contents of each tab on the System details page (Advisor, Vulnerability, etc.). This also updates the list of permissions according to the stage, not prod, RBAC config, and makes exception for org. admins to always show the tab contents.
Have an account for which you can alter roles/permissions. Go to /inventory and any system's details page. Leave only the Inventory Read role, and verify that all tabs except General and Advisor are unavailable (should write no access). Try …

fix(ESSNTL-5253): Change required permissions for tabs

---

src/components/InventoryTable/InventoryTable.cy.js
src/components/filters/SearchableGroupFilter.js
src/components/filters/__snapshots__/useGroupFilter.test.js.snap
src/components/filters/useGroupFilter.js
src/components/filters/useGroupFilter.test.js

Implements https://issues.redhat.com/browse/ESSNTL-4494.
This enhances the group filter for InventoryTable: the group options are now can be searched.
This changes the filter type to 'custom', but I tried to keep all of the input/return values of `useGroupFilter` untouched so that it's easier to integrate.
Try to search for your groups using this filter and apply any of them and check whether the table is filtered correctly. You can also use keyboard (arrows, tab, enter) to navigate within the filter. The placeholder text also should show correct values in different scenarios when there are items found or not. The filter chips must be synchronised with the filter selected values too.
The filter is updated also at the group details view, add to group modal (everywhere where InventoryTable …

feat(ESSNTL-4494): Implement searchable group filter

---

src/App.scss
src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js
src/components/InventoryGroups/GetHelpExpandable.js
src/components/InventoryGroups/GetHelpExpandable.scss
src/components/InventoryGroups/InventoryGroups.cy.js
src/components/InventoryGroups/InventoryGroups.js
src/components/InventoryGroups/NoGroupsEmptyState.js
src/routes/InventoryGroups.test.js

Implements https://issues.redhat.com/browse/RHIF-282.
This adds some helping notes on the top of the groups table. The second link must be hidden if user is not an org admin nor user access adminstrator.

feat(RHIF-282): Render get help expandable

---

src/components/filters/useLastSeenFilter.js

A patternfly updated affected the params that the datepicker uses, causing the component not to work anymore with just the 'date' param. This PR fixes that.
To test simply head to /systems page, enable the custom filter, and make sure the filter works as expected

fix(ESSNTL-5315): Fix last seen filter

---

src/components/InventoryDetail/ApplicationDetails.js
src/routes/InventoryDetail.js

Simple PR just introduces the spinner for when entitys is not loaded and there are no tabs yet. 
This also adds a default value for the osSlug in the case where the Os system is undefined/ not returned in the api

chore(loadingState): Loading state in AppDetails

---

src/components/InventoryGroups/GetHelpExpandable.js

Implements https://issues.redhat.com/browse/RHIF-282.
This connects the links in the Inventory groups "Get help" expandable with the right quick-starts IDs (see https://github.com/RedHatInsights/quickstarts/tree/main/docs/quickstarts).
Go to /inventory/groups; and try to click on both links. The quick-starts should pop up in the right page section.

feat(RHIF-282): Connect Inventory groups quick-starts

---

src/components/InventoryHostStaleness/constants.js

The 'Never' string wasnt converted in the form validations, so error messages/validation wasnt working as it should.
This PR updates var names and adds that conversion + styling on error messages for the first dropdowns.
To test navigate to the staleness and cullings page 
play around with the dropdowns.
The dropdown to the left should never be allowed to go higher than the dropdown to its right.
Staleness < Stale warning < Culling

fix(RHIN-447): Update Staleness form validation

---

src/components/InventoryDetail/DetailRenderer.js
src/components/InventoryDetail/DetailWrapper.js

Fixes https://issues.redhat.com/browse/ESSNTL-5468, https://issues.redhat.com/browse/ESSNTL-5469, https://issues.redhat.com/browse/ESSNTL-5470.
The DetailRenderer component shows a header with system basic information. The component is shared across more apps (see the attached tickets), and there has been an issue validating permissions for ungrouped systems. For ungrouped hosts, the component was wrongly checking for general hosts:write permissions instead of using `null` in resource definition as a minimum required permission.
Now, when a host is not a part of any group, the header renders correct information if the user has enough permissions.
The easiest way to test is to merge this PR and see it deployed in stage-preview :D Or to run some of the apps locally together with Inventory …

fix(ESSNTL-5468): Check for ungrouped hosts in DetailRenderer

---

src/components/InventoryHostStaleness/HostStalenessCard.js
src/components/InventoryHostStaleness/constants.js

This PR simply changes text. Removes 'culling' from the vocabulary on this page with the word 'deletion' as the page is now called Staleness and Deletion

fix(RHIN-447): Change text from culling to deletion

---

config/dev.webpack.config.js
config/prod.webpack.config.js
src/Utilities/constants.js
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.test.js
src/components/InventoryTabs/HybridInventoryTabs.js
src/modules/HybridInventoryTabs.js
src/routes/InventoryTable.js
src/routes/InventoryTable.test.js

This exposes the new HybirdInventoryTabs though fed-mods so that other apps can consume. Also preserves the URL parameters when a user comes back from another tab.
To test:
1. open Systems page
2. on conventional systems tab, change a page so that there is URL parameter active
3. navigate to immutable devices tab
4. navigate back to conventional tab
5. observe that the URL parameters  are still present in the URL in the conventional systems tab

chore(RHIF-277): expose HybridInventoryTabs as fed-mod, preserve URLs

---

src/components/InventoryTable/InventoryTable.js

RESOLVES: https://issues.redhat.com/browse/RHIF-313
Fixes the table not reflecting the active page parameter in the URL. 
Other URL parameters also need to be tested. I did not face issues with them except OS. I have observed that the active OS URL parameter is not reflected in the table, but this is not related to the hybrid tab as other apps are nicely handled. Recent CentOS filtering might have some influence. Created a bug for this: https://issues.redhat.com/browse/RHIF-314
To test: 
1. Navigate to stage/preview env
2. navigate to the insights-inventory 
3. apply some filters and change a page
4. Observe that URL params are added into the URL
5. Copy the URL and open the same page using copied URLs in another tab
6. observe that the URL params, especially the page param, are not …

fix(RHIF-313): fix not seeding url param page in Inventory page

---

cypress/support/interceptors.js
src/components/InventoryTabs/HybridInventoryTabs.cy.js
src/components/InventoryTabs/HybridInventoryTabs.js

This reverts commit 8ae09e192cf7e805e5e4d1679e44568cb83b5b3c.
Yesterday, there were issues with merged commits and I reverted 2 of them for a fast EE deployments fix. I am bringing them back today, will merge this after all checks pass

chore(RHIF-277): add cypress rest coverages for HybridInventoryTabs

---

config/prod.webpack.config.js

Attempt to fix the current broken inventory UI. Theoretically, this should be the cause of the issue as we are using only one container for both types of code. But, let's try this out
This makes sure beta assets are fetched from `beta/apps` path.

chore(prodConfig): enable beta/stable difference for deployments

---

src/api/api.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
src/components/filters/useOperatingSystemFilter.js
src/components/filters/useOperatingSystemFilter.test.js
src/store/inventory-actions.js

Only inventory and tasks need to see centos versions in the operating system filter on the inventory table. All other apps will not be fetching centos systems, so they don't need them in the dropdown.
You can test this by running inventory with tasks and any other apps to make sure they show or are hidden.

fix(RHINENG-462-2): hide centos versions in os filter

---

src/Utilities/edge.js
src/components/InventoryGroupDetail/NoSystemsEmptyState.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
src/components/InventoryTabs/ImmutableDevices/EdgeDevicesView.js

In the context of edgeParity, when creating a new group and selecting that group we enter the group details view, because it has no systems added yet an empty state is displayed and Add systems button is displayed also to systems, this PR allow to add conventional and immutable systems in that view.
- This should not affect the main add systems button when systems exists in group that's why edgeParityIsAllowed key is added.
- Two feature flags has be taken into considerations 'edgeParity.inventory-list' and 'edgeParity.inventory-groups-enabled'.
- If there is no immutable systems the immutable tab is not shown.
- Label is added in the header when edgeParity is enabled to show the overall number of the selected systems.
- The constraint is also taken into account also, when the immutable …

feat(THEEDGE-3585): Allow immutable systems selection in group details empty state

---

src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js

In the context to Allow immutable systems selection in group details empty state
Fixes the space between the tab and toolbar so it's the same as used in conventional tab.
FIXES: https://issues.redhat.com/browse/THEEDGE-3585

feat(THEEDGE-3585): fixes immutable tab space

---

src/api/api.js
src/components/InventoryHostStaleness/HostStalenessCard.js
src/components/InventoryHostStaleness/__test__/InventoryHostStaleness.test.js
src/components/InventoryHostStaleness/constants.js
src/routes/InventoryHostStaleness.js

This updates the page to use the new RBAC checks from the mocks : https://miro.com/app/board/uXjVMzdWSVk=/
and also renders the tabs conditionally based on if the user has edge systems or not.
It also updates the tool tip with correct admin permission text

fix(ESSNTL-5537): Update RBAC for staleness page + tab conditional

---

src/Routes.js
src/Utilities/conventional.js

Inventory Systems should not display Zero state when account has immutable systems
FIXES: https://issues.redhat.com/browse/THEEDGE-3629

fix(THEEDGE-3629): should not display Zero state when has edge systems

---

src/components/InventoryTable/InventoryList.scss

This fixes issues colliding with the lightbulb:
Before:
After:

fix(InventoryTable): RHINENG-2325 - Remove unwanted padding/margin resets

---

src/components/InventoryGroupDetail/GroupTabDetails.js
src/components/InventoryGroupDetail/InventoryGroupDetail.js
src/components/InventoryTabs/ImmutableDevices/EdgeDevicesGroupView.js

This PR add a tab to group details when exists an edge host added to the group.
In case only edge devices the focus will be on immutable
In case only conventional, no tabs displayed

feat(THEEDGE-3581): add tab controls to display detail groups

---

src/Routes.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
src/components/InventoryTabs/HybridInventoryTabs.cy.js
src/components/InventoryTabs/HybridInventoryTabs.js
src/routes/InventoryTable.js

Improves the API requests scattered around components to check the presence of conventional and edge systems by sharing one request result through the react context provider.

chore(HybridInventoryTab): accept host counts instead of API request

---

src/components/InventoryTable/InventoryList.scss

Fixes https://issues.redhat.com/browse/RHIF-72.
- Changes the InventoryTable rows text to have font size 14 px.
- Fixes the actions (kebab) button styling so that it is equally distanced from both sides.
Before
After

fix(RHIF-72): Fix InventoryTable font size and actions button padding

---

src/Utilities/constants.js
src/components/InventoryHostStaleness/HostStalenessCard.js
src/components/InventoryHostStaleness/HostStalenessNoAccess.js
src/components/InventoryHostStaleness/constants.js
src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap

This PR adds an additional check to only send values that have been altered to the api.
It also removes 'unknown' as an option for the status filter.
[fix(](https://github.com/RedHatInsights/insights-inventory-frontend/commit/9b129838b85eee3a74807f20c83fa08c25f0c6d3)[RHINENG-2911](https://issues.redhat.com/browse/RHINENG-2911)[): Update values in staleness api request](https://github.com/RedHatInsights/insights-inventory-frontend/commit/9b129838b85eee3a74807f20c83fa08c25f0c6d3)
[fix(](https://github.com/RedHatInsights/insights-inventory-frontend/commit/19a7b0b16c868fec88a104134be31ef259a0a7c1)[ESSNTL-5595](https://issues.redhat.com/browse/ESSNTL-5595)[): remove unknown option in status filter](https://github.com/RedHatInsights/insights-inventory-frontend/commit/19a7b0b16c868fec88a104134be3 …

fix(Staleness): Update staleness page to match new backend specs

---

config/cypress.webpack.config.js
config/overrideChrome.js
cypress/support/interceptors.js
src/components/ImmutableDevices/ImmutableDevices.cy.js
src/components/ImmutableDevices/columns.js

This fixes existing bugs when users click on the image name on Immutable devices table. Before this change, it would take users to edge device detail page, after this change users will be taken to image details page in image-builder app.
To test:
1. run inventory and advisor applications
2. Open advisor recommendations and select **Decreased performance occurs when KVM and VMWare guests are not running with recommended tuned service configuration** which has immutable devices.
3. Click on Image name 
4. Observe that you are taken to image details page in image-builder app

fix(ImmutableDevices): image name should take to image details page

---

src/components/ImmutableDevices/ImmutableDevices.js

This PR adds [initialLoading](https://github.com/RedHatInsights/insights-inventory-frontend/blob/910cb2c9ebd7311c25d6980b1894132702b372b6/doc/props_table.md?plain=1#L109) prop to make sure tabs do not contain previous content.
To test:
1. run this PR with insights-advisor  [PR](https://github.com/RedHatInsights/insights-advisor-frontend/pull/1193).
2. Go to the recommendation details page that has both conventional and immutable devices. e.g **Decreased performance occurs when KVM and VMWare guests are not running with recommended tuned service configuration**
3. Change tabs
4. Observe that the table shows the initial loading state on the first mount

fix(ImmutableDevices): add initial loading prop

---

src/Routes.js
src/Utilities/hooks/useEdgeGroups.js
src/api/api.js
src/components/InventoryGroups/EdgeGroups.js
src/routes/InventoryOrEdgeComponent.js

this commit expose edge group component from edge,
and give the ability if important customer log in to the system and navigate to group screen, he will see edge group list instead of inventory

feat(inventroyGroup): THEEDGE-3693- implement edge group expostion

---

src/Routes.js
src/Routes.test.js
src/routes/InventoryOrEdgeComponent.js

Fixes https://issues.redhat.com/browse/RHINENG-3766.
this commit fix the title of group page

fix(TitleTable): RHINENG-3766: group title page in case inventory user log in

---

src/api/systemIssues.js
src/api/systemIssues.test.js
src/components/InventoryDetail/DetailWrapper.test.js
src/components/InventoryDetailDrawer/SystemIssues.test.js

https://issues.redhat.com/browse/RHINENG-3395
Patchman v1 and v2 APIs will be turned off on 01/01/2024 so we need to update the version. The new version is backwards compatible (no parameters are removed/changed, only added).

Update Patchman API to v3

---

src/components/GroupsTable/GroupsTable.cy.js
src/components/GroupsTable/GroupsTable.js

Fixes https://issues.redhat.com/browse/RHINENG-1423.
Adds sorting by last modified on the groups page.
1. Go to /inventory/groups
2. Try to sort some groups by the "Last modified" column, verify that the results are correct
3. Make sure the sorting persists after page refresh

fix(RHINENG-1423): Enable sorting by last modified

---

src/api/edge/updates.js
src/components/InventoryGroupDetail/EdgeUpdateDeviceModal.js
src/components/InventoryGroupDetail/GroupDetailHeader.js
src/components/InventoryGroupDetail/__tests__/GroupDetailHeader.test.js

In the context of edge parity, add update action to global menu dropdown.
FIXES: https://issues.redhat.com/browse/THEEDGE-3539

feat(InventoryGroupDetails): THEEDGE-3539-Add update action to group details

---

src/components/InventoryGroups/Modals/CreateGroupModal.js
src/components/InventoryGroups/Modals/CreateGroupModal.test.js

Fixes https://issues.redhat.com/browse/ESSNTL-5418.
1. Go to /groups and click create a new group
2. Try to add a name of existing group and also add some whitespaces before/after the name
3. The modal should not allow you to create a group

fix(ESSNTL-5418): Trim group name before validate

---

src/components/ImmutableDevices/ImmutableDevices.cy.js
src/components/ImmutableDevices/ImmutableDevices.js
src/components/InventoryTable/EntityTable.js
src/components/InventoryTable/EntityTable.test.js
src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTable/TitleColumn.js
src/components/InventoryTable/TitleColumn.test.js
src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
src/components/InventoryTable/__snapshots__/TitleColumn.test.js.snap
src/components/InventoryTable/helpers.js
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
src/store/entities.js

This changes the `a` tag used to a proper react router `Link` component and allows entities to have a `href` prop that the Inventory should link the `display_name` (example in compliance[0]).
[0] https://github.com/RedHatInsights/compliance-frontend/pull/2012/files#diff-09ae52efeffb58d25e728921c02f75f65b9f249855e9eea936ce9e913d6997e1R145

feat(TitleColumn): RHINENG-3112 - Allow passing in a link via href prop

---

cypress/support/commands.js
package-lock.json
package.json
src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupsTable/GroupsTable.cy.js
src/components/ImmutableDevices/ImmutableDevices.cy.js
src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/components/InventoryGroups/InventoryGroups.cy.js
src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
src/components/InventoryGroups/Modals/CreateGroupModal.cy.js
src/components/InventoryGroups/Modals/DeleteGroupModal.cy.js
src/components/InventoryGroups/Modals/RenameGroupModal.cy.js
src/components/InventoryTable/InventoryTable.cy.js
src/components/InventoryTabs/HybridInventoryTabs.cy.js
src/routes/InventoryDetail.cy.js
src/routes/InventoryTable.cy.js

This is an attempt to fix the coverage random error happening on Travis CI while executing component tests.

test: Use a different way to update window object in tests

---

src/Routes.js
src/Utilities/hooks/useEdgeGroups.js
src/components/InventoryGroupDetail/EdgeGroupDetails.js
src/routes/InventoryOrEdgeGroupDetailsComponent.js

Implements https://issues.redhat.com/browse/THEEDGE-3707
this commit expose edge group details component from edge,
and give the ability if important customer log in to the system and navigate to group details screen from edge group screen, he will see edge group list instead of inventory and then be able to open group details

fix(InventoryGroupDetails): THEEDGE-3707 implement edge group details expostion

---

src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/InventoryTable.cy.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
src/components/filters/SearchableGroupFilter.js
src/components/filters/SearchableGroupFilter.test.js
src/components/filters/useGroupFilter.js
src/components/filters/useGroupFilter.test.js

Implements https://issues.redhat.com/browse/RHINENG-1850.
This updates the `useGroupFilter` hook to support the no group option. The /inventory and /groups/%id (in the Add systems modal) tables are updated and now allow users to filter out hosts that are not a part of any group.
⚠️ The option is disabled by default: this means it will not appear in other applications by default because non-HBI services do not yet support this feature.
1. Go to /inventory or /groups/%id (in the Add systems modal) and check that you can filter out ungrouped hosts
2. Try to reload the page (/inventory only) and make sure that the filter is still there.

feat(RHINENG-1850): Filtering ungrouped hosts

---

config/overrideChrome.js
config/setupTests.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroupDetail/index.js
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
src/components/filters/useGlobalFilter.js

Implements https://issues.redhat.com/browse/RHINENG-4614.
This extracts global filter handling to a separate hook and integrates it with the group details (/groups/%id) and also inventory (/inventory) pages.
1. Go to any group and try to filter out systems by workloads, tags and other global parameter. The results should be consistent (apply tags with the global filter => the table should contain only hosts with this tag).
2. Also, since the /inventory view is also refactored, make sure the global filter works there as expected.

feat(RHINENG-4614): Enable global filter on group details page

---

src/components/GeneralInfo/BiosCard/__snapshots__/BiosCard.test.js.snap
src/components/GeneralInfo/CollectionCard/__snapshots__/CollectionCard.test.js.snap
src/components/GeneralInfo/ConfigurationCard/__snapshots__/ConfigurationCard.test.js.snap
src/components/GeneralInfo/GeneralInformation/GeneralInformation.test.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
src/components/GeneralInfo/LoadingCard/LoadingCard.js
src/components/GeneralInfo/LoadingCard/__snapshots__/LoadingCard.test.js.snap
src/components/GeneralInfo/OperatingSystemCard/__snapshots__/OperatingSystemCard.test.js.snap
src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap

A regression happened from latest changes (https://github.com/RedHatInsights/insights-inventory-frontend/pull/1968) when used in federated mode, preventing the model dialogs to open, as no way in federated mode to find the modelId. 
This PR revert the change related of using useParams in function "Clickable" and add the full pathname to the url, also needed as in federated mode the path was truncated for example when used in edge-management app the path was "/edge/ipv4", with this change the path is correct and looks like "/edge/inventory/9ea55e32-6e30-4288-bf08-0a877c7fd306/ipv4" 
FIXES: https://issues.redhat.com/browse/THEEDGE-3764

fix(THEEDGE-3764): fixes LoadingCard component

---

src/components/GroupSystems/GroupImmutableSystems.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js

Show both tabs when adding systems to group, when adding conventional systems, conventional tab should be selected by default and when adding immutable systems, immutable tab should be selected by default. 
FIXES: https://issues.redhat.com/browse/THEEDGE-3758

feat(THEEDGE-3758): show both tabs when adding systems to group

---

src/components/GroupSystems/GroupImmutableSystems.js

Fix validation to avoid exception for navigate.
Check if deviceImageSet is filled before find the imae value

fix(THEEDGE-3757): add validation to imageset

---

src/components/GroupSystems/GroupImmutableSystems.js
src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
src/components/InventoryGroups/Modals/RemoveHostsFromGroupModal.js

Fixes https://issues.redhat.com/browse/RHINENG-2392.
This adds a refresh link to the success notification when systems are added or removed from a group. The data is no longer reloaded automatically due to possible inconsistency in the results.
⚠️ When adding new systems, the view is still refreshed under submit. This will be fixed in a separate PR/ticket.
1. Go to any group details page
2. Try to remove or add new systems
3. Check that the success notification has a refresh action and on click the page is reloaded with updated results

fix(RHINENG-2392): Show refresh link in group notifications

---

src/components/InventoryGroupDetail/InventoryGroupDetail.js
src/store/groupDetail.js

Fixes https://issues.redhat.com/browse/RHINENG-715.
Redirect back to /groups if non-existent group is visited.
1. Go to any group details page
2. Delete the group
3. Make sure you are redirected to /groups
4. Make sure if you navigate back to the group details page you are again redirected to /groups

fix(RHINENG-715): Redirect on non-existent group

---

src/Routes.js
src/components/GroupSystems/GroupSystems.cy.js
src/components/GroupSystems/GroupSystems.js
src/components/InventoryTable/InventoryTable.js
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
src/components/filters/useOnRefresh.js
src/components/filters/useOnRefresh.test.js
src/constants.js
src/routes/InventoryTable.js
src/store/reducers.js

Implements https://issues.redhat.com/browse/RHINENG-4606.
This enables URL updates on the group details page when filtering or pagination changes. Also, the filters are built on page refresh if there are any parameters present in URL.
1. Go to any group details page
2. Apply any filter, pagination and make sure it is reflected in URL
3. Refresh the page and verify that the same filters are applied.

feat(RHINENG-4606): Synchronise URL with applied table filters - group systems table

---

src/Routes.js
src/Routes.test.js

Fixes https://issues.redhat.com/browse/RHINENG-5953.
- The zero state component is now correctly rendered if there are no conventional nor immutable systems available for account. 
- This also adds isLoading flag to Routes to indicate the state when the component does not know yet about the number of systems available yet. It prevents Inventory from premature routes render.
1. Use an account without any hosts available
2. Go to /inventory and make sure you see the zero state banner, the inventory shouldn't load any route content.
3. Also make sure there is no tables render before zero state appears. This PR sets the loading flag before all the hosts number requests are fulfilled.

fix(RHINENG-5953): Fix zero state not loading on no systems

---

src/api/api.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/InfrastructureCard/InfrastructureCard.js
src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
src/components/GeneralInfo/selectors/selectors.js

Add Public IP & FQDN to Infrastructure Card in Host Details Page
The necessary changes that address the issue described on the ticket
Associated Jira ticket: [#RHINENG-4796](https://issues.redhat.com/browse/RHINENG-4796) 
Ensure a host containing the properties `public_ipv4_addresses` (& `public_dns`) is presenting those properties on its Infrastructure Card in its Host Details page
(It could also be with two different hosts that each contain one property)
Expected Functionality: 
- Hosts that have a property, should present it.
- Hosts that do not have a property, should present 'Not available' instead.
To test, you can search for a host named `lior_test_ip-172-31-89-28.ec2.internal` on `insights-qa` account. 
This host contains the necessary `public_ipv4_addresses` property that should …

Feat(RHINENG-4796): Add Public IP & FQDN to Infrastructure Card in Host Details Page

---

src/Utilities/TagsModal.js

Hi! Just noticed that `TagsModal` renders undefined if I don't have `display_name` set for my connected system, figured I can help improve it, let me know if tests are also needed but it's fairly minor change (I looked up the other properties in `SystemCard` component).
This is the UI problem now:

Render host or id if display_name not available in TagsModal

---

src/api/api.js

Add filter by host type as default to avoid list immutable and edge in the same list

fix(THEEDGE-3790): fix conventional filter when no host typ informed

---

src/components/GroupSystems/GroupImmutableSystems.js

When systems to update was selected the Update button was not updated as expected. 
Now the button is enabled when the selected systems are updatable and have the same image set, in all other cases the button is disabled. 
FIXES: https://issues.redhat.com/browse/THEEDGE-3782
[Screencast from 2024-01-10 13-24-37.webm](https://github.com/RedHatInsights/insights-inventory-frontend/assets/131553/6c3845c7-066d-4346-a1a0-703b3abc4e1d)

fix(GroupDetails): THEEDGE-3782 - Fixes Group details edge Update button

---

src/Routes.js

Fixes https://issues.redhat.com/browse/RHINENG-7083.
This fixes the issue with users having no `inventory:hosts:read` permissions trying to access the /inventory page. Now, while checking for hosts count, if we get 403, we should proceed and set the loading flag to false. The permissions are further handled by the /inventory route again so it's safe.
⚠️ This is an intermediate (workaround) fix because of the time pressure (but the proper refactor PR will be open soon). 
1. Have no 'inventory:hosts:read' permissions for your account
2. Navigate to /inventory
3. If you have at least one host (conventional/immutable), you should see the table rendered
4. If you don't have any hosts, you should see the "zero stage"

fix(RHINENG-7083): Temporarily ignore 403 when checking hosts count

---

src/components/GroupSystems/GroupImmutableSystems.js

According the ticket THEEDGE-3793, when we have a group with all the system "updated", we show on kebab menu the optiont o update as active. This is solved once a system with update pendent is added to the group.
The reason for this error is the deviceList been empty and it generate a false positive on the previous condition. This PR will fix the issue.

fix(THEEDGE-3793): Fix update option showed when all system are updated in a group

---

package-lock.json
package.json
src/Utilities/DeleteModal.js
src/Utilities/__snapshots__/DeleteModal.test.js.snap
src/Utilities/hooks/useBulkSelectConfig.js
src/components/GroupsTable/GroupsTable.js
src/components/InventoryGroups/Modals/DeleteGroupModal.js
src/components/InventoryHostStaleness/HostStalenessCard.js
src/components/InventoryTable/EntityTableToolbar.test.js
src/routes/inventory.scss

Fixes some of the bugs described in https://issues.redhat.com/browse/RHINENG-5932 comments.
This:
- On the staleness page, aligns the card title and popover
- Fixes all the icons that missed colours (danger, warning)
- On the groups page, aligns horizontally the Create group button with the rest of the toolbar
- Adds missing OUIA IDs and extends the OUIA coverage for the bulk select, conditional filter and actions in PrimaryToolbar.

fix(RHINENG-5932): Fix found visual regressions after PF5 migration

---

package.json

This should silence the semantic-release bot so that it doesn't add any released labels or comments to PRs which are misleading.
Docs: https://github.com/semantic-release/github, https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#plugin-options-configuration.

chore: Disable semantic-release comments and labels

---

src/components/GroupSystems/GroupImmutableSystems.js

Fixes https://issues.redhat.com/browse/RHINENG-8372.
The Immutable tab was playing up because of the deviceData being undefined or null which was not treated as a separate edge case.
1. Have a group with both conventional and immutable systems
2. Navigate to this group
3. Make sure you can switch between both immutable and conventional systems tabs without crash (which is reproducible on stage)

fix(RHINENG-8372): Fix Group details not loading Edge devices

---

src/components/InventoryDetail/FactsInfo.js
src/components/InventoryDetail/FactsInfo.test.js
src/components/InventoryDetail/InventoryDetail.scss
src/components/InventoryTable/ConversionPopover/ConversionPopover.js
src/components/InventoryTable/TitleColumn.js
src/components/InventoryTable/TitleColumn.test.js
src/components/InventoryTable/__snapshots__/TitleColumn.test.js.snap

Implements https://issues.redhat.com/browse/RHINENG-8561.
This adds a CentOS label to the inventory details and inventory list page. The label should appear for systems that are of CentOS Linux operating system.
1. Navigate to /inventory
2. Filter out CentOS systems and verify that you can see the label for each row
3. Click on any label and make sure more details are shown together with the button redirecting to Tasks
4. Click on any CentOS host and navigate to the host details page
5. Check that you can see a plain label after "Last seen"

feat(RHINENG-8561): Mark CentOS systems and provide more details

---

src/components/GeneralInfo/GeneralInformation/ConversionAlert.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.test.js

Implements https://issues.redhat.com/browse/RHINENG-8562.
This adds a banner for CentOS system on the host details page in Inventory. The first link leads to a documentation article, the second redirects to the tasks application.
1. Go to Inventory and find any CentOS system
2. Navigate to the system details page
3. Confirm you can see the alert

feat(RHINENG-8562): Show conversion alert for CentOS systems

---

src/components/GroupSystems/GroupSystems.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js

This PR addresses issue [#RHINENG-4108](https://issues.redhat.com/browse/RHINENG-4108)
When a user opens "Add systems" modal, the systems table filters are sometimes being reset when closing the modal
1. Visit https://console.stage.redhat.com/preview/insights/inventory/groups
2. Open any Group
3. Apply any filter to the Group's systems table
4. Click "Add systems" button
5. Close "Add systems" modal
Expected Results:
Systems table has previously applied filters
Actual Results:
Systems table sometimes doesn't have any filter when the modal closes

fix(RHINENG-4108): Filters are Being Reset When AddSystemsToGroupModal Closes

---

src/components/GeneralInfo/BootcImageCard/BootcImageCard.js
src/components/GeneralInfo/BootcImageCard/index.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
src/components/GeneralInfo/selectors/selectors.js
src/components/SystemDetails/GeneralInfo.js

Adds a new card with bootc system information.  It is hidden when the system is not a bootc system.
Note to reviewers:  Feel free to make changes directly.  Close and reopen a new PR if needed.  While I do believe this works and can be merged, its purpose is to imply intent.

feat(RHINENG-8881): Add bootc card host detail page

---

src/Utilities/constants.js
src/Utilities/edge.js
src/routes/InventoryComponents/BifrostPage.js
src/routes/InventoryComponents/BifrostTable.js
src/routes/InventoryComponents/BifrostTableColumns.js
src/routes/InventoryComponents/BifrostTableRows.js
src/routes/InventoryComponents/NestedHashTable.js
src/routes/InventoryPage.js
src/routes/InventoryPage.test.js
src/routes/inventory.scss

To test:
- Log into account with systems with bootc data
- Go to /insights/inventory url
- Click the toggle that is right-aligned in the Systems page header
From this point, you should see a table with expandable rows. Those expanded rows include specific hash data for each image name. The system counts  for the hash commits for the nested table should add up to equal the system counts for the parent image.
Please also ensure that the numbers in the system column line up for the table and nested table.

feat(RHINENG-9248): create bootc tree view

---

src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
src/components/SystemDetails/GeneralInfo.js

Hi! This PR adds a card to the General Information on the Inventory Systems page to display information from runtimes-inventory.
This "Application Services Proccesses" card resides in the [insights-runtimes-frontend](https://github.com/RedHatInsights/insights-runtimes-frontend) repository, and at the moment is only deployed in Stage (but will be looking to get into prod soon). The runtimes-inventory API returns application processes data given a hostname, so the card will need to be passed the `fqdn` from General Information. If no information exists or nothing is returned from the runtimes-inventory endpoint, the card will not display.
As for testing this functionality, there are two ways that I use at the moment:
1. Webpack custom proxy + locally hosted mock data
The …

feat(runtimes): add Runtimes Processes card to GeneralInformation

---

src/components/GeneralInfo/BootcImageCard/BootcImageCard.js
src/components/GeneralInfo/BootcImageCard/BootcImageCard.test.js
src/components/GeneralInfo/BootcImageCard/__snapshots__/BootcImageCard.test.js.snap
src/components/GeneralInfo/selectors/selectors.js

Adds available image and available image hash.

feat(RHINENG-9709): Add available image to bootc card

---

src/Utilities/constants.js
src/api/api.js
src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/TitleColumn.js
src/components/InventoryTable/__snapshots__/TitleColumn.test.js.snap
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
src/components/filters/index.js
src/components/filters/useSystemTypeFilter.js

Impements https://issues.redhat.com/browse/RHINENG-9687.
The new filter should only be visible to customers that have bootc images and when the feature is enabled. The filter should comply with the design in this mockup: https://www.figma.com/file/izOiimeI3i1a44dKEaFsUf/Systems-in-Bifrost?type=design&node-id=1016-41257&mode=design&t=ZYd83sqYOyalba6a-4
To test:
1. Run the PR
2. Navigate to the landing page in the Inventory page 
3. Observe that now there is a new 'System type' filter among others in the filters dropdown
4. Try filtering the table with package mode, observe that the request is made with `filter[system_profile][bootc_status][booted][image_digest]=nil`
5. Try filtering the table with image mode, and observe that the request is made with …

feat(RHINENG-9687): create system type filter

---

src/routes/InventoryComponents/InventoryPageHeader.js

This PR fixes the issue with the rounded edges of the ToggleGroupItems when a Tooltip is wrapped around the items. Adding the `triggerRef` removes the `<div>` that breaks the component.

fix(RHINENG-9686): border-radius in toggle group

---

package-lock.json
package.json
src/Utilities/hooks/useBulkSelectConfig.js

This version of frontend-components fixes the Spinner in the BulkSelect when loading all IDs. 
https://github.com/RedHatInsights/insights-inventory-frontend/assets/7757/8ae93c36-2706-4f90-a831-f83d0ed66807

fix(InventoryTable): RHINENG-8413 - Bump fec to fix BulkSelect

---

src/components/InventoryDetail/ApplicationDetails.js
src/components/InventoryDetail/DetailHeader.js
src/components/InventoryGroups/InventoryGroups.js
src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
src/routes/InventoryPage.js

While working on inventory I was annoyed by the amount of prop type/other errors. Fixed some of them.
Some components don't use certain props so I excluded them from the spread.
`Main` component from `frontend-components` was deprecated for a while.
How to test:
Make sure the green section is the same like on stage

fix: Prop types, unused props, replaced deprecated Main component

---

src/components/GeneralInfo/GeneralInformation/ConversionAlert.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.test.js
src/components/InventoryTable/ConversionPopover/ConversionPopover.js
src/components/InventoryTable/TitleColumn.js
src/components/InventoryTable/TitleColumn.test.js

Fixes https://issues.redhat.com/browse/RHINENG-9609, https://issues.redhat.com/browse/RHINENG-9611, https://issues.redhat.com/browse/RHINENG-9612.
This addresses more minor bugs found during last SPUR session.
Make sure the requirements from the tickets are met with this PR.
⚠️ I have omitted only one thing though: it's currently not possible to add extra padding to the conversions popover (see https://issues.redhat.com/browse/RHINENG-9611) easily due to the specifics of how popover component is mounted.

Fix Conversions layout/functional bugs after SPUR

---

src/components/InventoryHostStaleness/constants.js

Fixes https://issues.redhat.com/browse/RHINENG-9504.
After https://github.com/RedHatInsights/insights-inventory-frontend/pull/2189, we have removed some of the values that should have persisted. This PR is making sure we don't unnecessarily remove some values for staleness warning and deletion.

fix(RHINENG-9504): Return missing system stale and warning values

---

src/Utilities/hooks/useFetchBatched.js
src/components/InventoryTable/InventoryTable.test.js
src/components/filters/useGroupFilter.js
src/components/filters/useGroupFilter.test.js

[RHINENG-3920](https://issues.redhat.com/browse/RHINENG-3920)
Previously when the user didn't have `inventory:groups:read` permission he would get this error.
Now this request is only made when user has `inventory:groups:read` permission.
Test without sufficient permissions:
1. Make sure your account doesn't have `inventory:groups:read`. If you don't have such account, you can use `acelakov-groups-test` and the usual password
2. Go to Inventory > Systems
3. Check the groups filter, it should be empty and no request should be made to hosts.
Test with sufficient permissions:
1. User `acelakov-groups` has the correct permissions
2. Go to Inventory > Systems
3. Check the groups filter and it should be populated

fix(RHINENG-3920): Handle Groups 403

---

src/api/api.js

This fixes the global filter on the Systems and the systems table Group Details page.

fix(api): RHINENG-10393 - Prepend existing system_profile filters

---

src/routes/InventoryComponents/InventoryPageHeader.js
src/routes/InventoryComponents/InventoryPageHeader.test.js
src/routes/InventoryPage.test.js

No jira.
This returns the tooltip that should show up once users hover over "View by" buttons: view by systems, view by images.
Check on /inventory that the toggle has tooltips on hover.

fix(ContentToggle): Fix tooltips missing for "View by" buttons

---

src/__mocks__/selectors.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/SubscriptionCard/SubscriptionCard.js
src/components/GeneralInfo/SubscriptionCard/SubscriptionCard.test.js
src/components/GeneralInfo/SubscriptionCard/__snapshots__/SubscriptionCard.test.js.snap
src/components/GeneralInfo/SubscriptionCard/index.js
src/components/GeneralInfo/selectors/selectors.js

Description of problem: Unable to review what subscription information per host is uploaded to Insights
Steps to Reproduce:
1. Navigate to https://console.redhat.com/insights/inventory/
2. Click on any system from the list and view its information under 'General information' tab
Actual results: Unable to review the Subscription information of a system, the info page of a system is lacking subscription relevant information
Expected results: The system info page has also subscription information (service-level, purpose role, purpose usage, purpose addons)
Use case:
- Add system purpose Role and Usage to some of my servers
- Run the Inventory Sync from Satellite 6.9+
- Go to Insights Inventory to review if the Satellite uploaded the correct values

feat(RHINENG-358): Add subscription info to inv details

---

src/components/InventoryTable/TitleColumn.js
src/components/InventoryTable/__snapshots__/TitleColumn.test.js.snap

Currently` aria-label` is not visible for image mode icon is not visible in Inspect
with this change 'aria-label` should be visible in Inspect

fix(RHINENG-8684): Icon locator for image mode systems is not visible in Inspect

---

src/__mocks__/selectors.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.test.js
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/SubscriptionCard/SubscriptionCard.js
src/components/GeneralInfo/SubscriptionCard/SubscriptionCard.test.js
src/components/GeneralInfo/selectors/selectors.js

In the [previous PR](https://github.com/RedHatInsights/insights-inventory-frontend/pull/2208), we checked for systemProfile.system_purpose to find subscription info. But, we should be checking entity.facts instead.

fix(RHINENG-358): update selectors

---

src/components/GroupsTable/GroupsTable.js

On groups table, when you enter a filter that returns no groups, even if workspaces is enabled, it shows groups instead. This passes the correct "entities" to the NoEntitiesFound component depending on if the workspaces feature flag is enabled.

fix(RHINENG-10413): Fix no entities found

---

src/components/InventoryGroups/GetHelpExpandable.js
src/components/InventoryGroups/Modals/DeleteGroupModal.js

We need to fix it as https://github.com/RedHatInsights/quickstarts/pull/199 has been merged and metadata changed for Drawer

fix(InventoryDrawer): Fix onClick for inventory drawer

---

src/components/InventoryHostStaleness/BaseDropDown.js
src/components/InventoryHostStaleness/TabCard.js

This adds OUIA IDs to the staleness dropdown (both on the conventional and immutable tabs).

chore(Staleness): Add OUIA IDs for dropdowns

---

src/components/GroupSystems/GroupSystems.cy.js

Improve beforeEach queries to look at the rows text directly instead of asserting on the table OUIA safe property.

test(GroupSystems.cy.js): Reduce flakiness

---

src/components/GeneralInfo/GeneralInformation/ConversionAlert.js
src/components/GeneralInfo/GeneralInformation/GeneralInformation.test.js
src/components/InventoryTable/ConversionPopover/ConversionPopover.js
src/components/InventoryTable/TitleColumn.test.js

Fixes https://issues.redhat.com/browse/RHINENG-10825.
Use correct (newly updated) slug for the conversion analysis task. The change covers the label and popover at /inventory and the host details page alert.
1. Go to /inventory
2. Filter out CentOS Linux hosts and find the label next to the host display name
3. Click on the label and then on the button to get redirected to Tasks
4. The correct task modal must be open
5. Do the same for /inventory/:id page for some CentOS Linux host and the alert that should prompt the same action

fix(RHINENG-10825): Use correct slug to the conversion analysis

---

src/components/GroupSystems/GroupImmutableSystems.js
src/store/inventory-actions.js

Resolves: https://issues.redhat.com/browse/RHINENG-10975
Please test this thoroughly as I found it hard to reproduce locally.
To test:
1. Navigate to /workspaces list page
2. On stage environment find some workspace with immutable systems added
3. Navigate to its detail page
4. Switch to immutable tab
5. Observe that the page functions as expected and you only see those added immutable systems in the table

fix(RHINENG-10975): remove unused items variable in customGetEntities

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/EntityTableToolbar.test.js

Some applications using the `InventoryTable` provide an export of systems, in these cases we should not override the passed export config for the toolbar.
1) Ensure the `hbi.export-data` feature flag is enabled
2) Open an application that provides a custom export (Vulnerability, Compliance for example) on the "Systems" page
3) Verify that the CSV/JSON export is possible
4) Open the Inventory Systems page and verify that the export is still available there too.

fix(InventoryTable): RHINENG-11904 -  Preserve a passed exportConfig

---

src/App.scss

Fixes the padding issue inside vulnerability sys details page:
To replicate the issue, just go to any sysdetails in vulnerability
before there is a massive gap inbetween the table and header:

fix(vulnerability): Fix padding issue in vuln sysdetails page

---

src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/hooks/useInventoryExport.js

This corrects the resource name for the export service.
1) Open Systems page (for conventional systems)
2) Trigger an export, either CSV/JSON
3) Verify that the export request was submitted and a "prepare export" notification appeared.

fix(InventoryTable): RHINENG-9871 - Correct export resource

---

fec.config.js

No jira. This fixes the IS_DEV flag being always false. insights-chrome assigns "production" value if there is a production build or leaves it undefined in other cases (including the development build).

fix: Change condition for the IS_DEV flag

---

src/components/filters/useTextFilter.js

https://issues.redhat.com/browse/RHINENG-4792
Fixed the following bug:
1. Go to Systems page
2. Type " " (space) inside the search text field
3. Filter chip appears, but it shouldn't

fix(RHINENG-4792): Don't show filter chip for whitespace

---

src/Utilities/OperatingSystemFilterHelpers.js
src/Utilities/__snapshots__/OperatingSystemFilterHelpers.test.js.snap
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/InventoryTable.cy.js
src/components/InventoryTable/InventoryTable.test.js
src/components/filters/__snapshots__/useOperatingSystemFilter.test.js.snap
src/components/filters/useOperatingSystemFilter.js
src/components/filters/useOperatingSystemFilter.test.js
src/components/filters/useRegisteredWithFilter.js
src/components/filters/useRegisteredWithFilter.test.js
src/components/filters/useRhcdFilter.js
src/modules/OsFilterHelpers.js

Filter labels, placeholders and chips should use `Sentence case`, not `Title Case`
- Operating System --> Operating system
- Data Collector --> Data collector
Also fixed strict lower casing
- Filter by rhc status --> Filter by RHC status

fix(filters): Fix letter casing in filters

---

src/Utilities/TagsModal.js
src/constants.js

To test:
- Go to inventory
- Find a system with tags (preferrably one with more than 10 tags)
- Click the tags icon to open the Tags Modal
- Change the pagination details in any way
- Close the Tags Modal
If you click on the tags icon of another system, you will see that the pagination details persist. This PR resets the pagination defaults on closing the modal.

fix(RHINENG-11167): Fix pagination in Tags Modal

---

src/Routes.js

Fixes https://issues.redhat.com/browse/RHINENG-10516
This removes all occurrences of the "hbi.custom-staleness" feature flag. The flag is no longer planned to switch, and the feature is considered stable in production.

chore(RHINENG-10516): Remove staleness feature flag

---

src/Utilities/constants.js
src/components/GeneralInfo/DataCollectorsCard/__snapshots__/DataCollectorsCard.test.js.snap
src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/filters/useRegisteredWithFilter.test.js

This PR addresses [RHINENG-2632](https://issues.redhat.com/browse/RHINENG-2632). It separates the Satellite and Discovery data collectors. This change is needed ASAP because incoming host payloads now use the "satellite" and "discovery" values rather than "yupana".

fix(RHINENG-2632): Separate Satellite and Discovery data collectors

---

doc/props_table.md
src/Utilities/hooks/useFetchOperatingSystems.js
src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/InventoryTable.test.js
src/components/filters/useOperatingSystemFilter.js
src/components/filters/useOperatingSystemFilter.test.js

This allows the operating systems filter to fetch OS versions from a custom endpoint. This is yet a proposal and open for feedback.
To test:
1. run the PR linked with compliance PR https://github.com/RedHatInsights/compliance-frontend/pull/2192
2. make sure you have enabled REST api in compliance app
3. navigate to systems page
4. observe that now operating systems are fetched from compliance api and the filter versions are displayed
5. apply any os version
6. navigate to policy detail page
7. observe that now operating systems are fetched from compliance api with policy id provided.
8. play with the filter
9. now make sure that the operating system filter continues to function as before in all other apps.

feat(OperatingSystem): enhance the filter to fetch custom endpoint

---

src/components/InventoryGroups/InventoryGroups.js

Remove double scrollbars in Inventory Workspaces page 
bug was present only in Chromium browsers

fix(styles): RHINENG-11305 remove double scrollbar in Groups page

---

src/components/InventoryTable/InventoryList.scss

I have looked around inventory and it css piece I removed doesn't affect it at all. But this is going to make Compliance look better on Report details page. I also found out that Compliance had extra space on the right side from compact pagination, it's also fixed here
After:

fix(RHINENG-13776): Fix unnecessary toolbar items space

---

src/components/InventoryTable/Pagination.js
src/components/InventoryTable/__snapshots__/Pagination.test.js.snap

Currently bottom pagination contains `items` word. This started happening after PF5 migration and we don't want to see items there

fix(RHINENG-8675): Remove 'items' on bottom pagination

---

src/components/InventoryTable/InventoryList.scss

fix(RHINENG-13857): Make tags aligned with table header

---

src/components/InventoryDetail/InsightsPrompt.js

The details page for a system not registered with Insights is not pointing to the main source of information for registering the system. We should include a link to 'Registration Assistant'.
To test, navigate to inventory and click on the name of a system that is not registered (yellow icon). A link to the registration assistant should be provided as this is the main location to find information on how to register your system. The banner at the top of the page should include "How to register with insights-client?", and it should link to Registration Assistant app.

fix(RHINENG-11788): Add reg assistant link to sys details

---

src/components/GeneralInfo/TextInputModal/TextInputModal.js
src/components/GeneralInfo/TextInputModal/TextInputModal.test.js
src/components/GeneralInfo/TextInputModal/__snapshots__/TextInputModal.test.js.snap

It is possible to set both Display name and Ansible hostname to a space character, ' '. Not only this makes the UI confusing, it makes you unable to click the host in the Systems page: you have to click Edit, change the name and only then you can open the host details.
Trailing whitespace is cleaned on some places, but not consistently; display name "test   " is stored as such.
To test, find a system and click the system to view its details. Edit the display name and ansible hostname values.
This PR disables the Save button if the name hasn't changed, or is empty, including only whitespaces. Also, if you add whitespace before or after the string, it will trim the whitespace on both sides.

fix(RHINENG-12953): strip whitespace edit display and ansible hostname

---

src/components/InventoryHostStaleness/HostStalenessCard.js
src/components/InventoryHostStaleness/__test__/InventoryHostStaleness.test.js

https://issues.redhat.com/browse/RHINENG-13293
On page load, setIsLoading would fire BEFORE all of the calls were completed because these are all asychronous functions returning promises. They were starting and setIsLoading would fire without them being completed. 
Each call needs to be awaited to ensure the async functions are completed before firing off the setIsloading(false);
To test just navigate to staleness and deletion page and observe the drop downs on page load. They should only load in with data, and never display undefined.
Before: 
After: (just an example, data can be different depending on the account.

fix(RHINENG-13293): Fix undefined values on staleness page while loading

---

.github/workflows/main.yml

This adds a sentry hook, to work more as a button. A manual job with an input, being the commit hash, that will upload source maps with that specific build

Create Sentry workflow for source maps

---

.github/workflows/main.yml
fec.config.js

Updates flow to always inject debugID, and update the workflow file to remove overriding of release in sentry, and map against debug IDs properly

fix(sentry): Update sentrys workflow and always inject debugIDs

---

cypress/support/component.js
package-lock.json
package.json
src/components/InventoryTable/EntityTableToolbar.test.js
src/components/InventoryTable/hooks/useInventoryExport/useInventoryExport.js

Changes the text of the export dropdown according to the Jira.
**Before:**
**After:**

feat(InventoryTable): RHINENG-15246 - Reword export dropdown items

---

src/routes/InventoryComponents/BifrostPage.js
src/routes/InventoryComponents/BifrostPage.test.js

A regression happened where when you load the images table, it would remain in a persistent loading state. This PR fixes that issue.
To test:
- go to `/inventory` and click the images button for "View by images"
See that the table constantly shows loading state, but the fetch happens.

fix(RHINENG-15627): Images table persistent loading

---

.github/workflows/main.yml
fec.config.js

This also removes the issue where the plugin is initialized locally and sends up debugIDs for local env on every build
**Workflow Behavior:**
**Locally (without variables):**
The Sentry plugin won't build as SENTRY_AUTH_TOKEN/ENABLE_SENTRY is not defined.
**GitHub push to master (automatic trigger):**
The plugin won't include the authToken because commit_hash is not provided in push events.
**Manually triggered with commit_hash:**
The plugin includes the authToken and tracks the build with Sentry.

fix(sentry): Update sentry flow

---

src/components/InventoryHostStaleness/BaseDropDown.js
src/components/InventoryHostStaleness/__test__/BaseDropdown.test.js

This makes BaseDropdown to properly pass the OUIA ID prop. This was broken due to PF upgrades and end of direct `data-ouia-component-id` support.
Fixes https://issues.redhat.com/browse/RHINENG-15591.

fix(RHINENG-15591): Fix OUIA ID passing for BaseDropdown component

---

src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/LoadingCard/LoadingCard.js
src/components/GeneralInfo/SystemCard/SystemCard.js
src/components/GeneralInfo/SystemCard/SystemCard.test.js

Added Workspace to SystemCard in System detail page
Steps to test:
1. Go to System detail page
2. Observe System properties card - Workspace field
- Not available on a system not assigned to a workspace
- link to a workspace on a system assigned to a workspace 
Before:

feat(RHINENG-11178): add workspace to system detail card

---

src/components/InventoryGroups/GetHelpExpandable.js

No jira.
The workspaces page had infinite quickstarts tab open also triggering new requests.

fix(Workspaces page): Fix infinite quickstarts open

---

src/api/api.js

Fixes https://issues.redhat.com/browse/RHINENG-15918.
This is an additional PR to the ticket to also fix the way how we pass additional params to GET /hosts queries.
Fields are still passed with _options.params_ and not with just _fields_, since JS client's _fields_ transforms it into query not recognisable by HBI (e.g., { fields.system_profile = 'operating_system' } will turn into fields.system_profile=operating_system param which is not acceptable, we should use the current standard and use brackets instead of dot for nested params).
Make sure that all custom fields are passed with the GET /hosts request. For example, operating_system field is present and the response (and thus, Inventory table) contains OS version for every host.

fix(RHINENG-15918): Fix fields not being passed with hosts request

---

src/api/hostInventoryApi.ts
src/components/InventoryGroups/Modals/CreateGroupModal.js
src/components/InventoryGroups/utils/api.js
src/components/InventoryHostStaleness/HostStalenessCard.js

Fixes https://issues.redhat.com/browse/RHINENG-16620, https://issues.redhat.com/browse/RHINENG-16578.
This adds missing endpoints handlers and also makes it pass params correctly. This fixes the group creation and resetting staleness settings to default values.
You must be able to create a group. You must be able to reset staleness settings to default values.

fix: Fix bugs with staleness and groups endpoints handlers

---

src/components/InventoryTable/hooks/useColumns.js

We use `columnsProp`, so it needs to be a dependency. 
1) Open the Inventory Systems page
2) Navigate to the Workspaces and to a workspace details page (**with systems**)
3) You should see the "Update method" column
4) Navigate to the Inventory Systems page
5) You should **not*& see the "Update method" column

fix(InventoryTable): RHINENG-16584 - Add columnsProp to effect dependencies

---

src/components/GroupSystems/helpers.js

Fixes duplicate and unnecessary "update_method" columns in SytemsTable.
How to test:
1) Open the Inventory Systems page
2) Navigate to the Workspaces and to a workspace details page (with systems)
3) You should see the "Update method" column
4) Open the "add systems" modal and add systems to the workspace and save.
5) Navigate to the Inventory Systems page
6) You should *not& see any "Update method" columns

fix(GroupSystems): RHINENG-16584 - Copy array to not mutate columns

---

src/components/InventoryHostStaleness/BaseDropDown.js

`onSelected()` method assigned selected item's `name` instead of the `value`, which caused that `getNameByValue(selected) `always returned `undefined`. However, the `undefined` text was visible only if user had selected item from menu, that had been already selected - that was the only case, when `useEffect()` reacting on `currentItem`'s change didn't override the `undefined` text.

fix(RHINENG-16066): Custom staleness menu displays undefined when selecting already selected value

---

src/Utilities/TagsModal.js
src/Utilities/TagsModal.test.js
src/store/entities.js

This fixes issues in applications like Compliance and Tasks, where the TagsModal misbehaves. 
The reason for this is that these applications do not use the inventory/insights ID of the systems as the `id` prop for their rows in the `InventoryTable`.
Changing the issue in the applications for them to use the inventory ID as `id` property might cause issues as these might rely on the `id` prop being their app specific systems ID. 
This PR adds properties ( id, insightsId, insights_id) to the lookup of the entity to set as activeSystemTag.
It also makes the setting of activeSystemTag more explicit to ensure the correct data is used in the modal even if the other data set exists.
1) Run the Inventory with this PR
2) Open the Systems page
2.1) Verify the "tags links" in the …

fix(TagsModal): RHINENG-12940 - Set activeSystemTag more explicitly

---

src/components/InventoryDetail/FactsInfo.js
src/components/InventoryDetail/FactsInfo.test.js

OsModeLabel should not be displayed on Edge systems

fix(OSModeLabel): don't display on edge systems

---

src/Utilities/hooks/useFetchBatched.js
src/components/filters/SearchableGroupFilter.js
src/components/filters/useGroupFilter.js

This solves the issue described in Jira and ensures the workspace filter is kept up to date with the values available/fetched.
**How to test**
1) Open the Systems table with an account that has more than 10-20 groups
2) Select the "Workspace" filter
3) Verify the filter is properly filled with values.

fix(GroupFilter): RHINENG-16140 - Use deps and memoise properly

---

src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/SystemCard/SystemCard.js
src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.js
src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.test.js
src/components/GeneralInfo/SystemStatusCard/__snapshots__/SystemStatusCard.test.js.snap
src/components/GeneralInfo/TitleWithPopover.js
src/constants.js

This PR adds a tooltip to the RHC status on the inventory details screen. To test, go to Inventory -> System Details and see the RHC property of the System status card. The property should now have an icon and the text should match:
"The displayed RHC status indicates that the RHC client is installed and configured but may not reflect actual connectivity. For further troubleshooting, please visit Automation Toolkit > Remediations."

chore(RHINENG-16241): Add help tooltip to RHC status

---

src/components/InventoryGroupDetail/InventoryGroupDetail.js
src/components/InventoryGroupDetail/helpers/getHostsCount.js
src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
src/components/InventoryGroups/helpers/defaultConventionalSystemsGetEntities.js
src/components/InventoryGroups/helpers/defaultImmutableSystemsGetEntities.js

This fixes https://issues.redhat.com/browse/RHINENG-16137. When adding new hosts to workspace, in the Conventional tab, only conventional systems must be listed.

fix(RHINENG-16137): Use host type filter 'nil' when adding hosts

---

src/components/GeneralInfo/SystemStatusCard/SystemStatusCard.test.js
src/constants.js

This PR updates popover text to the RHC status on the inventory details screen. To test, go to Inventory -> System Details and see the RHC property of the System status card. The property should now have an icon and the text should match:
```
The RHC client was installed and configured but may not reflect actual connectivity.
To view the remediation status of your system, got to Automation Toolkit
> Remediations and open a remediation that your system is associated
with. Under the Systems tab, you will find the Connection Status.
```

fix(RHINENG-16241): Update text in rhc popover

---

src/components/InventoryTable/EntityTableToolbar.js
src/components/InventoryTable/EntityTableToolbar.test.js

While I was trying to find the root cause of https://github.com/RedHatInsights/compliance-frontend/pull/2239 , I found out that inventory has it's own thing.
Issue is super minor but it happens when you search by name on Inventory table and then you reset filters - but you can see that API requests will still contain `hostname_or_id: ` with empty value
To reproduce:
1. Navigate to Inventory systems table
2. Search by name
3. Open devtools network tab and observe it while clicking on reset filters
Request before:
`https://console.stage.redhat.com/api/inventory/v1/hosts?hostname_or_id=&per_page....`
Request after:
`https://stage.foo.redhat.com:1337/api/inventory/v1/hosts?per_page...`

fix(InventoryTable): Set activeFilter only when filter exist

---

cypress/support/interceptors.js
src/components/InventoryGroupDetail/GroupTabDetails.js
src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
src/components/InventoryGroupDetail/InventoryGroupDetail.js

This is an extra PR to fix the group details page wrongly displaying empty state. The empty state was not showing "No systems added" when there were no hosts in such group. This adds "groupName" to one of the useEffect dependencies so that the request to hosts count is done correctly only when group name is available.
Open an empty group, make sure the page shows "No groups added" message.

fix(RHINENG-16137): Fix wrong empty state when no hosts in group

---

src/routes/InventoryDetail.js

Disable Compliance tab for Conventonal image mode systems as Compliance doesn't support these.
1. Navigate to inventory systems -> Conventional tab
2. Filter systems by system type "Image mode"
3. Open system details page
4. Observe that Compliance tab is disabled

fix(RHINENG-15978): Disable Compliance tab for image mode systems

---

src/constants.js

Table used in modals (Inventory > System's Details > CPU flags || SAP IDs) doesn't clear search input after removing filters. This PR should fix it.

fix(RHINENG-11371): Clear text input after reseting filters in InfoTable

---

src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
src/components/GeneralInfo/LoadingCard/LoadingCard.js
src/components/GeneralInfo/SystemCard/SystemCard.js
src/components/GeneralInfo/SystemCard/SystemCard.test.js
src/components/GeneralInfo/SystemCard/SystemCardConfigs.js
src/components/GeneralInfo/SystemCard/SystemCardTestsFixtures.js
src/components/GeneralInfo/SystemCard/Workloads.js
src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
src/components/GeneralInfo/dataMapper/dataMapper.js
src/components/GeneralInfo/dataMapper/dataMapper.test.js

https://issues.redhat.com/browse/RHINENG-14652
1) Added functions that read workloads data from system profile and collect all the workloads that are present
2) Added a new field for workloads to the SystemCard.js, if workoads is present in workloadTypes it will render a clickable link that opens a modal for this workload.
3) Added a new data mapper that consumes the workloads data and populates the table
4) Wrote new tests for the mapper
How to test:
1)Replace workloadsData in SystemCard.js to the content of mockWorkloadsData from dataMapper.test.js
2)Open inventory, open any system
3)Check that there is a new Workloads field in the System properties card
4)Check the content of the modals and try to open them.
Screenshots:

feat(RHINENG-14652): Add workloads field to the system props card

---

src/components/GeneralInfo/SystemCard/SystemCard.test.js
src/components/GeneralInfo/SystemCard/SystemCardConfigs.js
src/components/GeneralInfo/SystemCard/SystemCardTestsFixtures.js
src/components/GeneralInfo/dataMapper/dataMapper.js
src/components/GeneralInfo/dataMapper/dataMapper.test.js

Fixes https://issues.redhat.com/browse/RHINENG-14652.
This renames Ansible to Ansible Automation Platform workload title. Also, the commit changes the way column titles are calculated for Inventory details page parameters tables.
Go to any host's Inventory details page, click through statuses, interfaces, workloads and other parameters that have a table list. Make sure the column names are correct. Also, verify that we use Ansible Automation Platform instead of just Ansible for workloads.

fix(RHINENG-14652): Fix column titles, rename Ansible workload

---

src/components/SystemDetails/Vulnerability.js

This change does not cause any issues, since Vulnerability accommodates both prop variants with and without a typo: https://github.com/RedHatInsights/vulnerability-ui/blob/a2eddb7ca2d811b32d718ee9fc1c0bd2229fd032/src/Components/SmartComponents/SystemCves/SystemCves.js#L287

chore: Fix typo in Vulnerability intl provider

---

src/constants.js
src/constants.test.js

The following modals have filter description using capital letters:
- Kernel modules: 'Filter by module'
- Installed packages: 'Filter by package name'
- Running processes: 'Filter by process name'
- Repositories: 'Filter by name' and  'Filter by enabled'
Always
Navigate to a system details page from system inventory Open one of the modal mentioned
Set a filter
The filter description will appear with capital letters.
Filter description should not have capital letters.

fix(RHINENG-11334): filter descriptions to lower case

---

src/routes/Systems/Systems.js
src/routes/Systems/components/SystemsTable/SystemsTable.js
src/routes/Systems/components/SystemsTable/SystemsTable.test.js
src/routes/Systems/components/SystemsTable/components/filters/Workspace.js
src/routes/Systems/components/SystemsTable/constants.js
src/routes/Systems/components/SystemsTable/filters.js
src/routes/Systems/components/SystemsTable/helpers.js
src/routes/Systems/helpers.js
src/routes/Systems/serialisers.js
tsconfig.json

Implements partially RHINENG-19947
PR is part of migration to TableTools in Inventory. It improves filter arg of SystemsTable and implements filters mentioned below with same functionality as original filters in inventoryTable.
Note 1: there are bits of Workspace and LastSeen filters introduced, I couldn't figure how to easily remove them. The code bits aren't being rendered though and will be used in following PR.  
Note 2: group selection is disabled for now in operating systems as it doesn't fully work because of underlying issue which is suspected to be between tabletools and frontend-component's conditional filter.
- pass filters as array or function which will be resolved
- basic filters - Name, Status, Data Collector, RHC status, Tags, System type, Operating systems

feat(RHINENG-19947): add basic filters to SystemsTable
